#!/bin/bash
# Quick deployment script for Support Inbox visibility fix

echo "=================================================="
echo "Support Inbox Visibility Fix - Deployment Guide"
echo "=================================================="
echo ""
echo "✅ Code changes have been pushed to GitHub (develop branch)"
echo ""
echo "📋 Next Steps:"
echo ""
echo "1. Apply Database Migration"
echo "   • Open Supabase Dashboard"
echo "   • Go to SQL Editor"
echo "   • Copy contents of: fix_support_inbox_visibility.sql"
echo "   • Execute the script"
echo ""
echo "2. Verify the Fix"
echo "   • Run the verification queries at the end of the SQL script"
echo "   • Check that is_admin() returns true for admin users"
echo "   • Check that support_threads are visible"
echo ""
echo "3. Test the Application"
echo "   As Shop User:"
echo "   • Go to Support Inbox → Send a test message"
echo ""
echo "   As Admin User:"
echo "   • Go to Point Catalog Management → User Feedback tab"
echo "   • You should now see the user's message!"
echo ""
echo "4. Deploy Backend Changes (if using Vercel/hosting)"
echo "   • Changes are already in 'develop' branch"
echo "   • Merge to 'main' or deploy from 'develop'"
echo ""
echo "=================================================="
echo "Files Changed:"
echo "=================================================="
echo "• fix_support_inbox_visibility.sql (SQL migration)"
echo "• FIX_SUPPORT_INBOX_VISIBILITY.md (documentation)"
echo "• app/src/app/api/admin/support/threads/route.ts"
echo "• app/src/app/api/admin/support/threads/[id]/route.ts"
echo "• app/src/app/api/admin/support/threads/[id]/reply/route.ts"
echo ""
echo "=================================================="
echo "Root Cause:"
echo "=================================================="
echo "The is_admin() function was checking for incorrect role codes."
echo "Expected: 'admin', 'super_admin', 'hq_admin'"
echo "Actual: 'SA', 'HQ', 'POWER_USER', 'HQ_ADMIN'"
echo ""
echo "This caused RLS policies to deny admin access to support data."
echo ""
echo "✅ Fix applied successfully!"
echo "=================================================="
