/**
 * Authorization coverage registry for every API route (Final Wave gate).
 * Generated from the source tree and reviewed; route-coverage.test.ts fails on
 * any route that is missing here or classified UNKNOWN, and on any ENTERPRISE
 * route whose file (or declared helper) does not reference its permission.
 *
 *   PUBLIC      unauthenticated by design (auth flows, public content)
 *   CONSUMER    consumer / loyalty participant identity, never enterprise RBAC
 *   SERVICE     cron, webhook, agent or integration credential (sa_service_identities)
 *   SELF        the caller's own record only
 *   ENTERPRISE  decided by Security & Access (permissions below)
 *   EXCEPTION   documented compatibility exception
 *   EMPTY       file without handlers
 */
export type RouteCoverage =
  | { kind: 'PUBLIC' | 'CONSUMER' | 'SERVICE' | 'SELF' | 'EXCEPTION' | 'EMPTY'; reason: string }
  | { kind: 'ENTERPRISE'; permissions: string[]; via?: string[] }

export const ROUTE_COVERAGE: Record<string, RouteCoverage> = {
  "accounting/accounts": { kind: 'ENTERPRISE', permissions: ["finance.account.manage", "finance.ledger.view"] },
  "accounting/accounts/[id]": { kind: 'ENTERPRISE', permissions: ["finance.account.manage", "finance.ledger.view"] },
  "accounting/accounts/[id]/toggle-active": { kind: 'ENTERPRISE', permissions: ["finance.account.manage"] },
  "accounting/accounts/seed": { kind: 'ENTERPRISE', permissions: ["finance.account.manage"] },
  "accounting/ap/aging": { kind: 'ENTERPRISE', permissions: ["finance.payable.view"] },
  "accounting/ap/bills": { kind: 'ENTERPRISE', permissions: ["finance.payable.view"] },
  "accounting/ap/payments": { kind: 'ENTERPRISE', permissions: ["finance.payable.view"] },
  "accounting/ar/aging": { kind: 'ENTERPRISE', permissions: ["finance.receivable.view"] },
  "accounting/ar/invoices": { kind: 'ENTERPRISE', permissions: ["finance.receivable.view"] },
  "accounting/ar/receipts": { kind: 'ENTERPRISE', permissions: ["finance.receivable.view"] },
  "accounting/cash/bank-accounts": { kind: 'ENTERPRISE', permissions: ["finance.cash.view", "finance.reconciliation.perform"] },
  "accounting/cash/cashflow": { kind: 'ENTERPRISE', permissions: ["finance.report.view_sensitive"] },
  "accounting/cash/reconciliation": { kind: 'ENTERPRISE', permissions: ["finance.cash.view", "finance.reconciliation.perform"] },
  "accounting/document-status/[id]": { kind: 'ENTERPRISE', permissions: ["finance.ledger.view"] },
  "accounting/exchange-rates": { kind: 'ENTERPRISE', permissions: ["finance.ledger.view", "finance.settings.manage"] },
  "accounting/fiscal-years": { kind: 'ENTERPRISE', permissions: ["finance.ledger.view", "finance.settings.manage"] },
  "accounting/fiscal-years/[id]": { kind: 'ENTERPRISE', permissions: ["finance.ledger.view", "finance.settings.manage"] },
  "accounting/fiscal-years/[id]/periods/[periodId]": { kind: 'ENTERPRISE', permissions: ["finance.settings.manage"] },
  "accounting/journals": { kind: 'ENTERPRISE', permissions: ["finance.ledger.view"] },
  "accounting/journals/[id]": { kind: 'ENTERPRISE', permissions: ["finance.ledger.view"] },
  "accounting/pending-postings": { kind: 'ENTERPRISE', permissions: ["finance.ledger.view"] },
  "accounting/posting": { kind: 'ENTERPRISE', permissions: ["finance.journal.post", "finance.ledger.view"] },
  "accounting/posting-rules": { kind: 'ENTERPRISE', permissions: ["finance.ledger.view", "finance.settings.manage"] },
  "accounting/reports/balance-sheet": { kind: 'ENTERPRISE', permissions: ["finance.report.view_sensitive"] },
  "accounting/reports/gl-detail": { kind: 'ENTERPRISE', permissions: ["finance.report.view_sensitive"] },
  "accounting/reports/profit-loss": { kind: 'ENTERPRISE', permissions: ["finance.report.view_sensitive"] },
  "accounting/reports/trial-balance": { kind: 'ENTERPRISE', permissions: ["finance.report.view_sensitive"] },
  "accounting/reset": { kind: 'ENTERPRISE', permissions: ["finance.data.reset"] },
  "accounting/settings": { kind: 'ENTERPRISE', permissions: ["finance.ledger.view", "finance.settings.manage"] },
  "accounting/status": { kind: 'ENTERPRISE', permissions: ["finance.module.view"] },
  "accounting/system-settings": { kind: 'ENTERPRISE', permissions: ["finance.ledger.view", "finance.settings.manage"] },
  "admin/adjustments/[id]/assign": { kind: 'ENTERPRISE', permissions: ["manufacturing.adjustment.manage"] },
  "admin/adjustments/[id]/status": { kind: 'ENTERPRISE', permissions: ["manufacturing.adjustment.manage"] },
  "admin/apply-migration": { kind: 'ENTERPRISE', permissions: ["platform.data.destructive"], via: ["lib/server/destructive-ops-guard.ts"] },
  "admin/apply-rls-fix": { kind: 'ENTERPRISE', permissions: ["platform.data.destructive"], via: ["lib/server/destructive-ops-guard.ts"] },
  "admin/bulk-delete-users": { kind: 'ENTERPRISE', permissions: ["platform.data.destructive"], via: ["lib/server/destructive-ops-guard.ts"] },
  "admin/categories/upload": { kind: 'ENTERPRISE', permissions: ["product.catalog.manage"] },
  "admin/cleanup/export": { kind: 'ENTERPRISE', permissions: ["platform.data.destructive"] },
  "admin/cleanup/runtime-report": { kind: 'ENTERPRISE', permissions: ["platform.data.destructive"] },
  "admin/cleanup/static-report": { kind: 'ENTERPRISE', permissions: ["platform.data.destructive"] },
  "admin/consumer-performance": { kind: 'ENTERPRISE', permissions: ["customer.consumer.view"] },
  "admin/delete-all-data": { kind: 'ENTERPRISE', permissions: ["platform.data.destructive"], via: ["lib/server/destructive-ops-guard.ts"] },
  "admin/delete-transactions-v2": { kind: 'ENTERPRISE', permissions: ["platform.data.destructive"], via: ["lib/server/destructive-ops-guard.ts"] },
  "admin/delete-user-otp/request": { kind: 'ENTERPRISE', permissions: ["platform.data.destructive"] },
  "admin/delete-user-otp/verify-and-delete": { kind: 'ENTERPRISE', permissions: ["platform.data.destructive"] },
  "admin/destructive-ops-status": { kind: 'PUBLIC', reason: "Environment capability flag only (no data)" },
  "admin/doc-migration": { kind: 'ENTERPRISE', permissions: ["platform.data.destructive"] },
  "admin/export-data": { kind: 'ENTERPRISE', permissions: ["platform.data.destructive"] },
  "admin/feedback": { kind: 'ENTERPRISE', permissions: ["customer.support.manage"] },
  "admin/fix-rls": { kind: 'ENTERPRISE', permissions: ["platform.data.destructive"], via: ["lib/server/destructive-ops-guard.ts"] },
  "admin/fix-shop-rls": { kind: 'ENTERPRISE', permissions: ["platform.data.destructive"] },
  "admin/migrate-rls": { kind: 'ENTERPRISE', permissions: ["platform.data.destructive"], via: ["lib/server/destructive-ops-guard.ts"] },
  "admin/migrate-user-points": { kind: 'EMPTY', reason: "Route file has no handlers" },
  "admin/point-migration": { kind: 'ENTERPRISE', permissions: ["customer.loyalty.adjust"] },
  "admin/point-migration-stream": { kind: 'ENTERPRISE', permissions: ["customer.loyalty.adjust"] },
  "admin/redemption-history": { kind: 'ENTERPRISE', permissions: ["customer.redemption.manage"] },
  "admin/redemptions": { kind: 'ENTERPRISE', permissions: ["customer.redemption.manage"] },
  "admin/restore-data": { kind: 'ENTERPRISE', permissions: ["platform.data.destructive"] },
  "admin/send-deletion-notification": { kind: 'ENTERPRISE', permissions: ["platform.data.destructive"] },
  "admin/setup-delete-function": { kind: 'ENTERPRISE', permissions: ["platform.data.destructive"], via: ["lib/server/destructive-ops-guard.ts"] },
  "admin/shop-consumers": { kind: 'ENTERPRISE', permissions: ["customer.consumer.view"] },
  "admin/shop-points-report": { kind: 'ENTERPRISE', permissions: ["customer.consumer.view"] },
  "admin/shop-requests": { kind: 'ENTERPRISE', permissions: ["platform.settings.manage"], via: ["app/api/settings/whatsapp/_utils.ts"] },
  "admin/shop-requests/[requestId]/approve": { kind: 'ENTERPRISE', permissions: ["platform.settings.manage"], via: ["app/api/settings/whatsapp/_utils.ts"] },
  "admin/shop-requests/[requestId]/reject": { kind: 'ENTERPRISE', permissions: ["platform.settings.manage"], via: ["app/api/settings/whatsapp/_utils.ts"] },
  "admin/shop-requests/settings": { kind: 'ENTERPRISE', permissions: ["platform.settings.manage"], via: ["app/api/settings/whatsapp/_utils.ts"] },
  "admin/shop-staff-performance": { kind: 'ENTERPRISE', permissions: ["customer.consumer.view"] },
  "admin/states": { kind: 'ENTERPRISE', permissions: ["platform.settings.manage"] },
  "admin/store/banners": { kind: 'ENTERPRISE', permissions: ["ecommerce.store.manage"] },
  "admin/store/banners/upload": { kind: 'ENTERPRISE', permissions: ["ecommerce.store.manage"] },
  "admin/store/hero-config": { kind: 'ENTERPRISE', permissions: ["ecommerce.store.manage"] },
  "admin/store/orders": { kind: 'ENTERPRISE', permissions: ["ecommerce.order.manage"] },
  "admin/support/admins": { kind: 'ENTERPRISE', permissions: ["customer.support.manage"] },
  "admin/support/blast": { kind: 'ENTERPRISE', permissions: ["customer.support.manage"] },
  "admin/support/blast/preview": { kind: 'ENTERPRISE', permissions: ["customer.support.manage"] },
  "admin/support/blast/stream": { kind: 'ENTERPRISE', permissions: ["customer.support.manage"] },
  "admin/support/conversations": { kind: 'ENTERPRISE', permissions: ["customer.support.manage"] },
  "admin/support/conversations/[id]": { kind: 'ENTERPRISE', permissions: ["customer.support.manage"] },
  "admin/support/conversations/[id]/messages": { kind: 'ENTERPRISE', permissions: ["customer.support.manage"] },
  "admin/support/conversations/[id]/notes": { kind: 'ENTERPRISE', permissions: ["customer.support.manage"] },
  "admin/support/conversations/[id]/tags": { kind: 'ENTERPRISE', permissions: ["customer.support.manage"] },
  "admin/support/tags": { kind: 'ENTERPRISE', permissions: ["customer.support.manage"] },
  "admin/support/threads": { kind: 'ENTERPRISE', permissions: ["customer.support.manage"] },
  "admin/support/threads/[id]": { kind: 'ENTERPRISE', permissions: ["customer.support.manage"] },
  "admin/support/threads/[id]/reply": { kind: 'ENTERPRISE', permissions: ["customer.support.manage"] },
  "admin/support/unread-count": { kind: 'ENTERPRISE', permissions: ["customer.support.manage"] },
  "admin/upload-template-preview": { kind: 'ENTERPRISE', permissions: ["platform.data.destructive"] },
  "admin/user-shop-migration": { kind: 'ENTERPRISE', permissions: ["customer.shop.manage"] },
  "admin/users/update-phone": { kind: 'EMPTY', reason: "Route file has no handlers" },
  "admin/whatsapp/admins": { kind: 'ENTERPRISE', permissions: ["platform.settings.manage"] },
  "admin/whatsapp/admins/[id]": { kind: 'ENTERPRISE', permissions: ["platform.settings.manage"] },
  "admin/whatsapp/ai-mode": { kind: 'ENTERPRISE', permissions: ["platform.settings.manage"] },
  "admin/whatsapp/config": { kind: 'ENTERPRISE', permissions: ["platform.settings.manage"] },
  "admin/whatsapp/settings": { kind: 'ENTERPRISE', permissions: ["platform.settings.manage"] },
  "admin/whatsapp/status": { kind: 'ENTERPRISE', permissions: ["platform.settings.manage"] },
  "agent/assist": { kind: 'SERVICE', reason: "Agent API authenticated by AGENT_API_KEY / WHATSAPP_AGENT_KEY (registered service identity)" },
  "agent/context": { kind: 'SERVICE', reason: "Agent API authenticated by AGENT_API_KEY / WHATSAPP_AGENT_KEY (registered service identity)" },
  "agent/orders": { kind: 'SERVICE', reason: "Agent API authenticated by AGENT_API_KEY / WHATSAPP_AGENT_KEY (registered service identity)" },
  "agent/points": { kind: 'SERVICE', reason: "Agent API authenticated by AGENT_API_KEY / WHATSAPP_AGENT_KEY (registered service identity)" },
  "agent/redeems": { kind: 'SERVICE', reason: "Agent API authenticated by AGENT_API_KEY / WHATSAPP_AGENT_KEY (registered service identity)" },
  "agent/search": { kind: 'SERVICE', reason: "Agent API authenticated by AGENT_API_KEY / WHATSAPP_AGENT_KEY (registered service identity)" },
  "ai/health": { kind: 'SELF', reason: "Caller's own profile, session and notification linking only" },
  "ai/metrics": { kind: 'ENTERPRISE', permissions: ["platform.settings.manage"] },
  "auth/oauth/[provider]/callback": { kind: 'PUBLIC', reason: "Social sign-in OAuth callback (authentication flow; state cookie validated)" },
  "auth/oauth/[provider]/start": { kind: 'PUBLIC', reason: "Social sign-in OAuth start (authentication flow, redirect only)" },
  "auth/password-reset/complete": { kind: 'PUBLIC', reason: "Authentication flows (sign-up, password reset, OTP verification)" },
  "auth/password-reset/request": { kind: 'PUBLIC', reason: "Authentication flows (sign-up, password reset, OTP verification)" },
  "auth/password-reset/resend": { kind: 'PUBLIC', reason: "Authentication flows (sign-up, password reset, OTP verification)" },
  "auth/password-reset/verify": { kind: 'PUBLIC', reason: "Authentication flows (sign-up, password reset, OTP verification)" },
  "auth/post-login-redirect": { kind: 'PUBLIC', reason: "Authentication flows (sign-up, password reset, OTP verification)" },
  "auth/register/check-availability": { kind: 'PUBLIC', reason: "Authentication flows (sign-up, password reset, OTP verification)" },
  "auth/register/request-code": { kind: 'PUBLIC', reason: "Authentication flows (sign-up, password reset, OTP verification)" },
  "auth/register/resend-code": { kind: 'PUBLIC', reason: "Authentication flows (sign-up, password reset, OTP verification)" },
  "auth/register/verify-code": { kind: 'PUBLIC', reason: "Authentication flows (sign-up, password reset, OTP verification)" },
  "auth/verify-password": { kind: 'PUBLIC', reason: "Authentication flows (sign-up, password reset, OTP verification)" },
  "bot/resolve-user": { kind: 'SERVICE', reason: "Agent API authenticated by AGENT_API_KEY / WHATSAPP_AGENT_KEY (registered service identity)" },
  "consumer/active-games": { kind: 'CONSUMER', reason: "Consumer loyalty/scan experience (consumer identity, not enterprise RBAC)" },
  "consumer/check-collection-status": { kind: 'CONSUMER', reason: "Consumer loyalty/scan experience (consumer identity, not enterprise RBAC)" },
  "consumer/check-lucky-draw-status": { kind: 'CONSUMER', reason: "Consumer loyalty/scan experience (consumer identity, not enterprise RBAC)" },
  "consumer/claim-gift": { kind: 'CONSUMER', reason: "Consumer loyalty/scan experience (consumer identity, not enterprise RBAC)" },
  "consumer/collect-points": { kind: 'CONSUMER', reason: "Consumer loyalty/scan experience (consumer identity, not enterprise RBAC)" },
  "consumer/collect-points-auth": { kind: 'CONSUMER', reason: "Consumer loyalty/scan experience (consumer identity, not enterprise RBAC)" },
  "consumer/feedback": { kind: 'CONSUMER', reason: "Consumer loyalty/scan experience (consumer identity, not enterprise RBAC)" },
  "consumer/link-shop": { kind: 'CONSUMER', reason: "Consumer shop affiliation for the signed-in store account only (session actor, active SHOP target, no role/scope change); never enterprise access" },
  "consumer/lucky-draw-entry": { kind: 'CONSUMER', reason: "Consumer loyalty/scan experience (consumer identity, not enterprise RBAC)" },
  "consumer/points-history": { kind: 'CONSUMER', reason: "Consumer loyalty/scan experience (consumer identity, not enterprise RBAC)" },
  "consumer/products": { kind: 'CONSUMER', reason: "Consumer loyalty/scan experience (consumer identity, not enterprise RBAC)" },
  "consumer/redeem-gifts": { kind: 'CONSUMER', reason: "Consumer loyalty/scan experience (consumer identity, not enterprise RBAC)" },
  "consumer/redeem-reward": { kind: 'CONSUMER', reason: "Consumer loyalty/scan experience (consumer identity, not enterprise RBAC)" },
  "consumer/redemption-history": { kind: 'CONSUMER', reason: "Consumer loyalty/scan experience (consumer identity, not enterprise RBAC)" },
  "consumer/rewards": { kind: 'CONSUMER', reason: "Consumer loyalty/scan experience (consumer identity, not enterprise RBAC)" },
  "consumer/scanned-products": { kind: 'CONSUMER', reason: "Consumer loyalty/scan experience (consumer identity, not enterprise RBAC)" },
  "consumer/track-scan": { kind: 'CONSUMER', reason: "Consumer loyalty/scan experience (consumer identity, not enterprise RBAC)" },
  "consumer/validate-security-code": { kind: 'CONSUMER', reason: "Consumer loyalty/scan experience (consumer identity, not enterprise RBAC)" },
  "cron/manufacturer-packing-worker": { kind: 'SERVICE', reason: "Cron/queue worker authenticated with CRON_SECRET (registered service identity)" },
  "cron/notification-outbox-worker": { kind: 'SERVICE', reason: "Cron/queue worker authenticated with CRON_SECRET (registered service identity)" },
  "cron/process-async-reverse": { kind: 'SERVICE', reason: "Cron/queue worker authenticated with CRON_SECRET (registered service identity)" },
  "cron/qr-generation-worker": { kind: 'SERVICE', reason: "Cron/queue worker authenticated with CRON_SECRET (registered service identity)" },
  "cron/qr-reverse-worker": { kind: 'SERVICE', reason: "Cron/queue worker authenticated with CRON_SECRET (registered service identity)" },
  "cron/sa-decision-retention": { kind: 'SERVICE', reason: "Cron/queue worker authenticated with CRON_SECRET (registered service identity)" },
  "cron/sa-governance-maintenance": { kind: 'SERVICE', reason: "Cron/queue worker authenticated with CRON_SECRET (registered service identity)" },
  "cron/serapp-hold-expiry": { kind: 'SERVICE', reason: "Cron/queue worker authenticated with CRON_SECRET (registered service identity)" },
  "cron/storefront-unpaid-expiry": { kind: 'SERVICE', reason: "Cron worker authenticated with CRON_SECRET: cancels Outdoor orders unpaid for 24 hours" },
  "cron/warehouse-debug": { kind: 'SERVICE', reason: "Cron/queue worker authenticated with CRON_SECRET (registered service identity)" },
  "cron/warehouse-receiving-worker": { kind: 'SERVICE', reason: "Cron/queue worker authenticated with CRON_SECRET (registered service identity)" },
  "debug/sms-provider-check": { kind: 'ENTERPRISE', permissions: ["platform.settings.manage"], via: ["app/api/settings/whatsapp/_utils.ts"] },
  "debug/supabase-check": { kind: 'ENTERPRISE', permissions: ["platform.data.destructive"] },
  "documents/[documentId]/acknowledge": { kind: 'ENTERPRISE', permissions: ["supply_chain.document.acknowledge"] },
  "documents/generate": { kind: 'ENTERPRISE', permissions: ["supply_chain.document.manage"] },
  "documents/manufacturer-upload": { kind: 'ENTERPRISE', permissions: ["supply_chain.document.manage"] },
  "documents/order/[orderId]/bundle": { kind: 'ENTERPRISE', permissions: ["supply_chain.document.manage"] },
  "documents/order/[orderId]/file": { kind: 'ENTERPRISE', permissions: ["supply_chain.document.manage"] },
  "documents/payment-request/[id]/approve": { kind: 'ENTERPRISE', permissions: ["finance.payment.approve"] },
  "email/send": { kind: 'ENTERPRISE', permissions: ["platform.settings.manage"] },
  "email/usage": { kind: 'ENTERPRISE', permissions: ["platform.settings.manage"] },
  "engagement/catalog/ellbow/adjust": { kind: 'ENTERPRISE', permissions: ["customer.loyalty.adjust", "customer.reward.manage"], via: ["lib/server/ellbow-catalog.ts"] },
  "engagement/catalog/ellbow/categories": { kind: 'ENTERPRISE', permissions: ["customer.reward.manage"], via: ["lib/server/ellbow-catalog.ts"] },
  "engagement/catalog/ellbow/participants/organizations": { kind: 'ENTERPRISE', permissions: ["customer.program.manage", "customer.reward.manage"], via: ["lib/server/ellbow-catalog.ts"] },
  "engagement/catalog/ellbow/participants/search": { kind: 'ENTERPRISE', permissions: ["customer.program.manage", "customer.reward.manage"], via: ["lib/server/ellbow-catalog.ts"] },
  "engagement/catalog/ellbow/participants/users": { kind: 'ENTERPRISE', permissions: ["customer.program.manage", "customer.reward.manage"], via: ["lib/server/ellbow-catalog.ts"] },
  "engagement/catalog/ellbow/public-rewards": { kind: 'PUBLIC', reason: "Public consumer journey, QR verification and branding content" },
  "engagement/catalog/ellbow/redeem": { kind: 'CONSUMER', reason: "Loyalty participant (shop/member) wallet and redemption — own balances" },
  "engagement/catalog/ellbow/redemptions": { kind: 'ENTERPRISE', permissions: ["customer.redemption.manage", "customer.reward.manage"], via: ["lib/server/ellbow-catalog.ts"] },
  "engagement/catalog/ellbow/reports/[report]": { kind: 'ENTERPRISE', permissions: ["customer.consumer.view", "customer.reward.manage"], via: ["lib/server/ellbow-catalog.ts"] },
  "engagement/catalog/ellbow/rewards": { kind: 'ENTERPRISE', permissions: ["customer.reward.manage"], via: ["lib/server/ellbow-catalog.ts"] },
  "engagement/catalog/ellbow/rewards/[id]": { kind: 'ENTERPRISE', permissions: ["customer.reward.manage"], via: ["lib/server/ellbow-catalog.ts"] },
  "engagement/catalog/ellbow/rewards/[id]/images": { kind: 'ENTERPRISE', permissions: ["customer.reward.manage"], via: ["lib/server/ellbow-catalog.ts"] },
  "engagement/catalog/ellbow/rewards/[id]/images/[imageId]": { kind: 'ENTERPRISE', permissions: ["customer.reward.manage"], via: ["lib/server/ellbow-catalog.ts"] },
  "engagement/catalog/ellbow/scans": { kind: 'CONSUMER', reason: "Loyalty participant (shop/member) wallet and redemption — own balances" },
  "engagement/catalog/ellbow/settings": { kind: 'ENTERPRISE', permissions: ["customer.reward.manage"], via: ["lib/server/ellbow-catalog.ts"] },
  "engagement/catalog/ellbow/shop": { kind: 'CONSUMER', reason: "Loyalty participant (shop/member) wallet and redemption — own balances" },
  "engagement/catalog/ellbow/transactions": { kind: 'CONSUMER', reason: "Loyalty participant (shop/member) wallet and redemption — own balances" },
  "engagement/catalog/ellbow/wallet": { kind: 'CONSUMER', reason: "Loyalty participant (shop/member) wallet and redemption — own balances" },
  "export/ellbow/catalog": { kind: 'SERVICE', reason: "Webhook / integration authenticated by a registered service credential (sa_service_identities)" },
  "finance/config/audit": { kind: 'ENTERPRISE', permissions: ["finance.module.view", "finance.settings.manage"] },
  "games/daily-quiz/submit": { kind: 'CONSUMER', reason: "Consumer loyalty/scan experience (consumer identity, not enterprise RBAC)" },
  "games/spin": { kind: 'CONSUMER', reason: "Consumer loyalty/scan experience (consumer identity, not enterprise RBAC)" },
  "get-client-ip": { kind: 'PUBLIC', reason: "Public consumer journey, QR verification and branding content" },
  "health": { kind: 'PUBLIC', reason: "Public consumer journey, QR verification and branding content" },
  "hr/accounting/control-accounts": { kind: 'ENTERPRISE', permissions: ["finance.payroll_integration.manage"] },
  "hr/accounting/mappings": { kind: 'ENTERPRISE', permissions: ["finance.payroll_integration.manage"] },
  "hr/accounting/preview-journal": { kind: 'ENTERPRISE', permissions: ["finance.payroll_integration.manage"] },
  "hr/ai/actions/[actionKey]": { kind: 'ENTERPRISE', permissions: ["hr.ai.use"] },
  "hr/ai/audit": { kind: 'ENTERPRISE', permissions: ["hr.ai.use"] },
  "hr/ai/chat": { kind: 'ENTERPRISE', permissions: ["hr.ai.use"] },
  "hr/analytics/kpis": { kind: 'ENTERPRISE', permissions: ["hr.analytics.view"] },
  "hr/analytics/reports": { kind: 'ENTERPRISE', permissions: ["hr.analytics.view"] },
  "hr/analytics/snapshots": { kind: 'ENTERPRISE', permissions: ["hr.analytics.view"] },
  "hr/assistant/chat": { kind: 'ENTERPRISE', permissions: ["hr.self_service.use"], via: ["lib/server/hrAccess.ts"] },
  "hr/assistant/chat/stream": { kind: 'ENTERPRISE', permissions: ["hr.self_service.use"], via: ["lib/server/hrAccess.ts"] },
  "hr/attendance/audit": { kind: 'ENTERPRISE', permissions: ["hr.attendance.manage"] },
  "hr/attendance/clock": { kind: 'ENTERPRISE', permissions: ["hr.self_service.use"], via: ["lib/server/hrAccess.ts"] },
  "hr/attendance/corrections": { kind: 'ENTERPRISE', permissions: ["hr.attendance.manage", "hr.self_service.use"], via: ["lib/server/hrAccess.ts"] },
  "hr/attendance/corrections/[id]/review": { kind: 'ENTERPRISE', permissions: ["hr.attendance.manage"] },
  "hr/attendance/entries": { kind: 'ENTERPRISE', permissions: ["hr.attendance.manage"] },
  "hr/attendance/overtime": { kind: 'ENTERPRISE', permissions: ["hr.attendance.manage"] },
  "hr/attendance/overtime/preview": { kind: 'SELF', reason: "Own KPI scorecards/reviews/dashboard (row ownership; manager and HR actions go through hr.performance.manage routes)" },
  "hr/attendance/overtime/requests": { kind: 'ENTERPRISE', permissions: ["hr.attendance.manage", "hr.self_service.use"], via: ["lib/server/hrAccess.ts"] },
  "hr/attendance/policy": { kind: 'ENTERPRISE', permissions: ["hr.attendance.manage"] },
  "hr/attendance/shifts": { kind: 'ENTERPRISE', permissions: ["hr.attendance.manage"] },
  "hr/attendance/shifts/[id]": { kind: 'ENTERPRISE', permissions: ["hr.attendance.manage"] },
  "hr/attendance/timesheets": { kind: 'ENTERPRISE', permissions: ["hr.attendance.manage"] },
  "hr/attendance/timesheets/[id]/approve": { kind: 'ENTERPRISE', permissions: ["hr.attendance.manage"] },
  "hr/attendance/timesheets/[id]/reject": { kind: 'ENTERPRISE', permissions: ["hr.attendance.manage"] },
  "hr/attendance/timesheets/[id]/submit": { kind: 'ENTERPRISE', permissions: ["hr.self_service.use"], via: ["lib/server/hrAccess.ts"] },
  "hr/benefits/contribution-runs": { kind: 'ENTERPRISE', permissions: ["hr.benefits.manage"] },
  "hr/benefits/enrollments": { kind: 'ENTERPRISE', permissions: ["hr.benefits.manage"] },
  "hr/benefits/plans": { kind: 'ENTERPRISE', permissions: ["hr.benefits.manage"] },
  "hr/benefits/providers": { kind: 'ENTERPRISE', permissions: ["hr.benefits.manage"] },
  "hr/compliance/acknowledgements": { kind: 'ENTERPRISE', permissions: ["hr.policy.manage", "hr.self_service.use"], via: ["lib/server/hrAccess.ts"] },
  "hr/compliance/contracts": { kind: 'ENTERPRISE', permissions: ["hr.contract.manage", "hr.contract.view"] },
  "hr/compliance/policies": { kind: 'ENTERPRISE', permissions: ["hr.policy.manage"] },
  "hr/config/audit": { kind: 'ENTERPRISE', permissions: ["hr.settings.manage"] },
  "hr/employees": { kind: 'ENTERPRISE', permissions: ["hr.employee.manage"] },
  "hr/employees/profile": { kind: 'ENTERPRISE', permissions: ["hr.employee.manage"] },
  "hr/finance/gl-mappings": { kind: 'ENTERPRISE', permissions: ["finance.payroll_integration.manage"] },
  "hr/finance/post-benefit-contribution-run": { kind: 'ENTERPRISE', permissions: ["finance.journal.post"] },
  "hr/finance/post-expense-claim": { kind: 'ENTERPRISE', permissions: ["finance.journal.post"] },
  "hr/finance/post-payroll-run": { kind: 'ENTERPRISE', permissions: ["hr.payroll.release"] },
  "hr/kpi/actuals": { kind: 'ENTERPRISE', permissions: ["hr.performance.manage"] },
  "hr/kpi/adjustments": { kind: 'SELF', reason: "Own KPI scorecards/reviews/dashboard (row ownership; manager and HR actions go through hr.performance.manage routes)" },
  "hr/kpi/adjustments/[id]/approve": { kind: 'ENTERPRISE', permissions: ["hr.performance.manage"] },
  "hr/kpi/assignments": { kind: 'ENTERPRISE', permissions: ["hr.performance.manage"] },
  "hr/kpi/assignments/[id]": { kind: 'ENTERPRISE', permissions: ["hr.performance.manage"] },
  "hr/kpi/dashboard": { kind: 'SELF', reason: "Own KPI scorecards/reviews/dashboard (row ownership; manager and HR actions go through hr.performance.manage routes)" },
  "hr/kpi/data-mappings": { kind: 'ENTERPRISE', permissions: ["hr.performance.manage"] },
  "hr/kpi/data-mappings/[id]/sync": { kind: 'ENTERPRISE', permissions: ["hr.performance.manage"] },
  "hr/kpi/data-mappings/[id]/validate": { kind: 'ENTERPRISE', permissions: ["hr.performance.manage"] },
  "hr/kpi/metrics": { kind: 'ENTERPRISE', permissions: ["hr.performance.manage"] },
  "hr/kpi/metrics/[id]": { kind: 'ENTERPRISE', permissions: ["hr.performance.manage"] },
  "hr/kpi/objectives": { kind: 'ENTERPRISE', permissions: ["hr.performance.manage"] },
  "hr/kpi/objectives/[id]": { kind: 'ENTERPRISE', permissions: ["hr.performance.manage"] },
  "hr/kpi/objectives/[id]/metrics": { kind: 'ENTERPRISE', permissions: ["hr.performance.manage"] },
  "hr/kpi/periods": { kind: 'ENTERPRISE', permissions: ["hr.performance.manage"] },
  "hr/kpi/periods/[id]": { kind: 'ENTERPRISE', permissions: ["hr.performance.manage"] },
  "hr/kpi/reports/heatmap": { kind: 'SELF', reason: "Own KPI scorecards/reviews/dashboard (row ownership; manager and HR actions go through hr.performance.manage routes)" },
  "hr/kpi/reports/summary": { kind: 'SELF', reason: "Own KPI scorecards/reviews/dashboard (row ownership; manager and HR actions go through hr.performance.manage routes)" },
  "hr/kpi/reviews": { kind: 'SELF', reason: "Own KPI scorecards/reviews/dashboard (row ownership; manager and HR actions go through hr.performance.manage routes)" },
  "hr/kpi/reviews/[id]": { kind: 'SELF', reason: "Own KPI scorecards/reviews/dashboard (row ownership; manager and HR actions go through hr.performance.manage routes)" },
  "hr/kpi/reviews/[id]/approve": { kind: 'ENTERPRISE', permissions: ["hr.performance.manage"] },
  "hr/kpi/reviews/[id]/manager": { kind: 'ENTERPRISE', permissions: ["hr.performance.manage"] },
  "hr/kpi/reviews/[id]/request-changes": { kind: 'ENTERPRISE', permissions: ["hr.performance.manage"] },
  "hr/kpi/reviews/[id]/self": { kind: 'SELF', reason: "Own KPI scorecards/reviews/dashboard (row ownership; manager and HR actions go through hr.performance.manage routes)" },
  "hr/kpi/scorecards": { kind: 'SELF', reason: "Own KPI scorecards/reviews/dashboard (row ownership; manager and HR actions go through hr.performance.manage routes)" },
  "hr/kpi/scorecards/[id]": { kind: 'SELF', reason: "Own KPI scorecards/reviews/dashboard (row ownership; manager and HR actions go through hr.performance.manage routes)" },
  "hr/kpi/scorecards/[id]/items/[itemId]/evidence": { kind: 'SELF', reason: "Own KPI scorecards/reviews/dashboard (row ownership; manager and HR actions go through hr.performance.manage routes)" },
  "hr/kpi/scorecards/[id]/recalculate": { kind: 'ENTERPRISE', permissions: ["hr.performance.manage"] },
  "hr/kpi/scorecards/generate": { kind: 'ENTERPRISE', permissions: ["hr.performance.manage"] },
  "hr/kpi/targets": { kind: 'ENTERPRISE', permissions: ["hr.performance.manage"] },
  "hr/kpi/targets/publish": { kind: 'ENTERPRISE', permissions: ["hr.performance.manage"] },
  "hr/learning/certifications": { kind: 'ENTERPRISE', permissions: ["hr.learning.manage"] },
  "hr/learning/courses": { kind: 'ENTERPRISE', permissions: ["hr.learning.manage"] },
  "hr/learning/enrollments": { kind: 'ENTERPRISE', permissions: ["hr.learning.manage"] },
  "hr/onboarding/instances": { kind: 'ENTERPRISE', permissions: ["hr.onboarding.manage"] },
  "hr/onboarding/tasks": { kind: 'ENTERPRISE', permissions: ["hr.onboarding.manage"] },
  "hr/onboarding/templates": { kind: 'ENTERPRISE', permissions: ["hr.onboarding.manage"] },
  "hr/payroll/allowance-types": { kind: 'ENTERPRISE', permissions: ["hr.compensation.manage", "hr.compensation.view"] },
  "hr/payroll/allowance-types/[id]": { kind: 'ENTERPRISE', permissions: ["hr.compensation.manage"] },
  "hr/payroll/compensation": { kind: 'ENTERPRISE', permissions: ["hr.compensation.manage", "hr.compensation.view"] },
  "hr/payroll/components": { kind: 'ENTERPRISE', permissions: ["hr.compensation.manage", "hr.compensation.view"] },
  "hr/payroll/deduction-types": { kind: 'ENTERPRISE', permissions: ["hr.compensation.manage", "hr.compensation.view"] },
  "hr/payroll/deduction-types/[id]": { kind: 'ENTERPRISE', permissions: ["hr.compensation.manage"] },
  "hr/payroll/employee-allowances": { kind: 'ENTERPRISE', permissions: ["hr.compensation.manage", "hr.compensation.view"] },
  "hr/payroll/employee-deductions": { kind: 'ENTERPRISE', permissions: ["hr.compensation.manage", "hr.compensation.view"] },
  "hr/payroll/post-to-gl": { kind: 'ENTERPRISE', permissions: ["hr.payroll.release"] },
  "hr/payroll/runs": { kind: 'ENTERPRISE', permissions: ["hr.payroll.prepare", "hr.payroll.view"] },
  "hr/payroll/runs/[id]/approve": { kind: 'ENTERPRISE', permissions: ["hr.payroll.approve"] },
  "hr/payroll/runs/[id]/calculate": { kind: 'ENTERPRISE', permissions: ["hr.payroll.prepare"] },
  "hr/payroll/runs/[id]/items": { kind: 'ENTERPRISE', permissions: ["hr.payroll.view"] },
  "hr/payroll/salary-bands": { kind: 'ENTERPRISE', permissions: ["hr.compensation.manage", "hr.compensation.view"] },
  "hr/payroll/salary-bands/[id]": { kind: 'ENTERPRISE', permissions: ["hr.compensation.manage"] },
  "hr/payroll/statutory-settings": { kind: 'ENTERPRISE', permissions: ["hr.compensation.manage", "hr.compensation.view"] },
  "hr/performance/appraisals": { kind: 'ENTERPRISE', permissions: ["hr.performance.manage"] },
  "hr/performance/reviews": { kind: 'ENTERPRISE', permissions: ["hr.performance.manage"] },
  "hr/performance/templates": { kind: 'ENTERPRISE', permissions: ["hr.performance.manage"] },
  "hr/positions": { kind: 'ENTERPRISE', permissions: ["hr.employee.manage"] },
  "hr/positions/[id]": { kind: 'ENTERPRISE', permissions: ["hr.employee.manage"] },
  "hr/positions/seed": { kind: 'ENTERPRISE', permissions: ["hr.employee.manage"] },
  "hr/public-holidays": { kind: 'ENTERPRISE', permissions: ["hr.settings.manage"] },
  "hr/recruitment/applicants": { kind: 'ENTERPRISE', permissions: ["hr.recruitment.manage"] },
  "hr/recruitment/applications": { kind: 'ENTERPRISE', permissions: ["hr.recruitment.manage"] },
  "hr/recruitment/interviews": { kind: 'ENTERPRISE', permissions: ["hr.recruitment.manage"] },
  "hr/recruitment/jobs": { kind: 'ENTERPRISE', permissions: ["hr.recruitment.manage"] },
  "hr/recruitment/offers": { kind: 'ENTERPRISE', permissions: ["hr.recruitment.manage"] },
  "hr/self-service/document-requests": { kind: 'ENTERPRISE', permissions: ["hr.self_service.use"], via: ["lib/server/hrAccess.ts"] },
  "hr/self-service/payslip-access": { kind: 'ENTERPRISE', permissions: ["hr.payroll.view"] },
  "hr/self-service/profile-change-requests": { kind: 'ENTERPRISE', permissions: ["hr.employee.manage", "hr.self_service.use"], via: ["lib/server/hrAccess.ts"] },
  "hr/settings/permissions": { kind: 'ENTERPRISE', permissions: ["hr.settings.manage"] },
  "hr/time-expense/claims": { kind: 'ENTERPRISE', permissions: ["hr.expense.manage"] },
  "hr/time-expense/entries": { kind: 'ENTERPRISE', permissions: ["hr.expense.manage"] },
  "hr/time-expense/items": { kind: 'ENTERPRISE', permissions: ["hr.expense.manage"] },
  "hr/time-expense/timesheets": { kind: 'ENTERPRISE', permissions: ["hr.expense.manage"] },
  "inventory/opening-balance/allocation-resolve": { kind: 'ENTERPRISE', permissions: ["inventory.opening_balance.manage", "inventory.stock_config.manage"], via: ["lib/server/stock-config-admin.ts"] },
  "inventory/opening-balance/carry-forward-preflight": { kind: 'ENTERPRISE', permissions: ["inventory.opening_balance.manage", "inventory.stock_config.manage"], via: ["lib/server/stock-config-admin.ts"] },
  "inventory/opening-balance/d2h-policy": { kind: 'ENTERPRISE', permissions: ["inventory.opening_balance.manage", "inventory.stock_config.manage"], via: ["lib/server/stock-config-admin.ts"] },
  "inventory/opening-balance/h2m-bulk": { kind: 'ENTERPRISE', permissions: ["inventory.opening_balance.manage", "inventory.stock_config.manage"], via: ["lib/server/stock-config-admin.ts"] },
  "inventory/opening-balance/h2m-incoming-preflight": { kind: 'ENTERPRISE', permissions: ["inventory.opening_balance.manage", "inventory.stock_config.manage"], via: ["lib/server/stock-config-admin.ts"] },
  "inventory/opening-balance/h2m-policy": { kind: 'ENTERPRISE', permissions: ["inventory.opening_balance.manage", "inventory.stock_config.manage"], via: ["lib/server/stock-config-admin.ts"] },
  "inventory/opening-balance/transactions-policy": { kind: 'ENTERPRISE', permissions: ["inventory.opening_balance.manage", "inventory.stock_config.manage"], via: ["lib/server/stock-config-admin.ts"] },
  "inventory/stock-configurations/bulk-eligible": { kind: 'ENTERPRISE', permissions: ["inventory.stock_config.manage"], via: ["lib/server/stock-config-admin.ts"] },
  "inventory/stock-configurations/bulk-enable": { kind: 'ENTERPRISE', permissions: ["inventory.stock_config.manage"], via: ["lib/server/stock-config-admin.ts"] },
  "inventory/stock-configurations/eligibility": { kind: 'ENTERPRISE', permissions: ["inventory.stock_config.manage"], via: ["lib/server/stock-config-admin.ts"] },
  "inventory/stock-configurations/variant/[variantId]": { kind: 'ENTERPRISE', permissions: ["inventory.stock_config.manage"], via: ["lib/server/stock-config-admin.ts"] },
  "inventory/stock-count/drafts/posting-status": { kind: 'ENTERPRISE', permissions: ["inventory.stock_count.view"] },
  "inventory/stock-count/verification/preflight": { kind: 'ENTERPRISE', permissions: ["inventory.stock_count.view"] },
  "inventory/stock-count/verification/request": { kind: 'ENTERPRISE', permissions: ["inventory.stock_count.verify"] },
  "inventory/stock-count/verification/verify": { kind: 'ENTERPRISE', permissions: ["inventory.stock_count.post", "inventory.stock_count.verify"] },
  "journey/auto-create": { kind: 'ENTERPRISE', permissions: ["customer.campaign.manage"] },
  "journey/create": { kind: 'ENTERPRISE', permissions: ["customer.campaign.manage"] },
  "journey/dashboard-summary": { kind: 'ENTERPRISE', permissions: ["customer.campaign.manage"] },
  "journey/default": { kind: 'PUBLIC', reason: "Public consumer journey, QR verification and branding content" },
  "journey/delete": { kind: 'ENTERPRISE', permissions: ["customer.campaign.manage"] },
  "journey/download-qr-excel": { kind: 'ENTERPRISE', permissions: ["customer.campaign.manage"] },
  "journey/duplicate": { kind: 'ENTERPRISE', permissions: ["customer.campaign.manage"] },
  "journey/effective": { kind: 'PUBLIC', reason: "Public consumer journey, QR verification and branding content" },
  "journey/engagement-trend": { kind: 'ENTERPRISE', permissions: ["customer.campaign.manage"] },
  "journey/list": { kind: 'ENTERPRISE', permissions: ["customer.campaign.manage"] },
  "journey/order-experience": { kind: 'ENTERPRISE', permissions: ["customer.campaign.manage"] },
  "journey/orders": { kind: 'ENTERPRISE', permissions: ["customer.campaign.manage"] },
  "journey/qr-stats": { kind: 'ENTERPRISE', permissions: ["customer.campaign.manage"] },
  "journey/update": { kind: 'ENTERPRISE', permissions: ["customer.campaign.manage"] },
  "landing-pages": { kind: 'ENTERPRISE', permissions: ["customer.campaign.manage"], via: ["lib/landing-pages/admin.ts"] },
  "landing-pages/[id]": { kind: 'ENTERPRISE', permissions: ["customer.campaign.manage"], via: ["lib/landing-pages/admin.ts"] },
  "landing-pages/[id]/archive": { kind: 'ENTERPRISE', permissions: ["customer.campaign.manage"], via: ["lib/landing-pages/admin.ts"] },
  "landing-pages/[id]/duplicate": { kind: 'ENTERPRISE', permissions: ["customer.campaign.manage"], via: ["lib/landing-pages/admin.ts"] },
  "landing-pages/[id]/metrics": { kind: 'ENTERPRISE', permissions: ["customer.campaign.manage"], via: ["lib/landing-pages/admin.ts"] },
  "landing-pages/[id]/publish": { kind: 'ENTERPRISE', permissions: ["customer.campaign.manage"], via: ["lib/landing-pages/admin.ts"] },
  "landing-pages/[id]/resolve-products": { kind: 'ENTERPRISE', permissions: ["customer.campaign.manage"], via: ["lib/landing-pages/admin.ts"] },
  "landing-pages/[id]/unpublish": { kind: 'ENTERPRISE', permissions: ["customer.campaign.manage"], via: ["lib/landing-pages/admin.ts"] },
  "landing-pages/events": { kind: 'PUBLIC', reason: "Public consumer journey, QR verification and branding content" },
  "landing-pages/product-options": { kind: 'ENTERPRISE', permissions: ["customer.campaign.manage"], via: ["lib/landing-pages/admin.ts"] },
  "logo": { kind: 'PUBLIC', reason: "Public consumer journey, QR verification and branding content" },
  "loyalty/memberships/organization": { kind: 'ENTERPRISE', permissions: ["customer.program.manage"] },
  "loyalty/memberships/organizations": { kind: 'ENTERPRISE', permissions: ["customer.program.manage"] },
  "lucky-draw/campaigns": { kind: 'ENTERPRISE', permissions: ["customer.campaign.manage"] },
  "lucky-draw/draw": { kind: 'ENTERPRISE', permissions: ["customer.campaign.manage"] },
  "lucky-draw/entries": { kind: 'ENTERPRISE', permissions: ["customer.campaign.manage"] },
  "lucky-draw/orders": { kind: 'ENTERPRISE', permissions: ["customer.campaign.manage"] },
  "manufacturer/adjustments": { kind: 'ENTERPRISE', permissions: ["manufacturing.adjustment.manage"] },
  "manufacturer/adjustments/[id]": { kind: 'ENTERPRISE', permissions: ["manufacturing.adjustment.manage"] },
  "manufacturer/adjustments/[id]/evidence/[index]": { kind: 'ENTERPRISE', permissions: ["manufacturing.adjustment.manage"] },
  "manufacturer/adjustments/[id]/send": { kind: 'ENTERPRISE', permissions: ["manufacturing.adjustment.manage"] },
  "manufacturer/adjustments/create": { kind: 'ENTERPRISE', permissions: ["manufacturing.adjustment.manage"] },
  "manufacturer/adjustments/evidence": { kind: 'ENTERPRISE', permissions: ["manufacturing.adjustment.manage"] },
  "manufacturer/async-reverse/job-status": { kind: 'ENTERPRISE', permissions: ["manufacturing.scan.reverse"] },
  "manufacturer/async-reverse/submit-job": { kind: 'ENTERPRISE', permissions: ["manufacturing.scan.reverse"] },
  "manufacturer/batch-progress": { kind: 'ENTERPRISE', permissions: ["manufacturing.production.manage"] },
  "manufacturer/bulk-pack": { kind: 'ENTERPRISE', permissions: ["manufacturing.production.manage"] },
  "manufacturer/check-master-codes": { kind: 'ENTERPRISE', permissions: ["manufacturing.production.manage"] },
  "manufacturer/complete-production": { kind: 'ENTERPRISE', permissions: ["manufacturing.production.manage"] },
  "manufacturer/debug-scan-history": { kind: 'ENTERPRISE', permissions: ["manufacturing.production.manage"] },
  "manufacturer/delete-scan-history": { kind: 'ENTERPRISE', permissions: ["manufacturing.scan.reverse"] },
  "manufacturer/get-batch-codes": { kind: 'ENTERPRISE', permissions: ["manufacturing.production.manage"] },
  "manufacturer/link-to-master": { kind: 'ENTERPRISE', permissions: ["manufacturing.production.manage"] },
  "manufacturer/link-to-master-from-queue": { kind: 'ENTERPRISE', permissions: ["manufacturing.production.manage"] },
  "manufacturer/mark-all-perfect": { kind: 'ENTERPRISE', permissions: ["manufacturing.production.manage"] },
  "manufacturer/mark-case-perfect": { kind: 'ENTERPRISE', permissions: ["manufacturing.production.manage"] },
  "manufacturer/modec/analyze-input": { kind: 'ENTERPRISE', permissions: ["manufacturing.production.manage"] },
  "manufacturer/modec/create-job": { kind: 'ENTERPRISE', permissions: ["manufacturing.production.manage"] },
  "manufacturer/modec/jobs": { kind: 'ENTERPRISE', permissions: ["manufacturing.production.manage"] },
  "manufacturer/modec/jobs/[jobId]": { kind: 'ENTERPRISE', permissions: ["manufacturing.production.manage"] },
  "manufacturer/modec/jobs/[jobId]/cancel": { kind: 'ENTERPRISE', permissions: ["manufacturing.production.manage"] },
  "manufacturer/modec/process-job": { kind: 'SERVICE', reason: "Cron/queue worker authenticated with CRON_SECRET (registered service identity)" },
  "manufacturer/reverse-job/status": { kind: 'ENTERPRISE', permissions: ["manufacturing.scan.reverse"] },
  "manufacturer/reverse-job/submit": { kind: 'ENTERPRISE', permissions: ["manufacturing.scan.reverse"] },
  "manufacturer/reverse-job/worker": { kind: 'SERVICE', reason: "Cron/queue worker authenticated with CRON_SECRET (registered service identity)" },
  "manufacturer/scan-history": { kind: 'ENTERPRISE', permissions: ["manufacturing.production.manage"] },
  "manufacturer/scan-summary-excel": { kind: 'ENTERPRISE', permissions: ["manufacturing.production.manage"] },
  "manufacturer/scan-unique": { kind: 'ENTERPRISE', permissions: ["manufacturing.production.manage"] },
  "manufacturer/start-packing": { kind: 'ENTERPRISE', permissions: ["manufacturing.production.manage"] },
  "manufacturer/unlink-master": { kind: 'ENTERPRISE', permissions: ["manufacturing.production.manage"] },
  "marketing/campaigns": { kind: 'ENTERPRISE', permissions: ["customer.campaign.manage"] },
  "marketing/test-send": { kind: 'ENTERPRISE', permissions: ["customer.campaign.manage"] },
  "master-banner": { kind: 'ENTERPRISE', permissions: ["customer.campaign.manage"] },
  "master-banner/[orgId]": { kind: 'PUBLIC', reason: "Public consumer journey, QR verification and branding content" },
  "master-banner/upload": { kind: 'ENTERPRISE', permissions: ["customer.campaign.manage"] },
  "message-setup/preview": { kind: 'ENTERPRISE', permissions: ["customer.campaign.manage"] },
  "message-setup/short-links": { kind: 'ENTERPRISE', permissions: ["customer.campaign.manage"] },
  "message-setup/short-links/[id]": { kind: 'ENTERPRISE', permissions: ["customer.campaign.manage"] },
  "message-setup/variables": { kind: 'ENTERPRISE', permissions: ["customer.campaign.manage"] },
  "messaging/fulfilment-items": { kind: 'ENTERPRISE', permissions: ["inventory.report.view"] },
  "messaging/preparation-items": { kind: 'ENTERPRISE', permissions: ["warehouse.shipment.manage"] },
  "messaging/receipt": { kind: 'ENTERPRISE', permissions: ["warehouse.receipt.post"] },
  "messaging/receipt/resolve": { kind: 'ENTERPRISE', permissions: ["warehouse.receipt.post"] },
  "messaging/settings-status": { kind: 'ENTERPRISE', permissions: ["platform.settings.manage"] },
  "messaging/timeline": { kind: 'ENTERPRISE', permissions: ["inventory.report.view"] },
  "messaging/warehouse-inbox": { kind: 'ENTERPRISE', permissions: ["inventory.report.view"] },
  "messaging/warehouse-inbox/action": { kind: 'ENTERPRISE', permissions: ["warehouse.shipment.manage"] },
  "module-assistant/chat": { kind: 'ENTERPRISE', permissions: ["hr.ai.use"] },
  "module-assistant/chat/stream": { kind: 'ENTERPRISE', permissions: ["hr.ai.use"] },
  "movements": { kind: 'ENTERPRISE', permissions: ["inventory.report.view"] },
  "notifications/order-event": { kind: 'ENTERPRISE', permissions: ["supply_chain.order.create"] },
  "notifications/recipients/preview": { kind: 'ENTERPRISE', permissions: ["platform.settings.manage"] },
  "notifications/resolve": { kind: 'ENTERPRISE', permissions: ["platform.settings.manage"] },
  "notifications/sms-check": { kind: 'ENTERPRISE', permissions: ["platform.settings.manage"], via: ["app/api/settings/whatsapp/_utils.ts"] },
  "notifications/test": { kind: 'ENTERPRISE', permissions: ["platform.settings.manage"], via: ["app/api/settings/whatsapp/_utils.ts"] },
  "notifications/test-send": { kind: 'ENTERPRISE', permissions: ["platform.settings.manage"] },
  "orders/[orderId]/access": { kind: 'EXCEPTION', reason: "Order visibility helper: relation-based (buyer/seller/HQ) read rule without mutation; orders RLS enforces tenancy" },
  "orders/[orderId]/ship-metrics": { kind: 'ENTERPRISE', permissions: ["inventory.report.view"] },
  "orders/actors": { kind: 'EXCEPTION', reason: "Order visibility helper: relation-based (buyer/seller/HQ) read rule without mutation; orders RLS enforces tenancy" },
  "orders/d2h/preflight": { kind: 'ENTERPRISE', permissions: ["supply_chain.order.create"] },
  "orders/d2h/quick-order-catalog": { kind: 'ENTERPRISE', permissions: ["supply_chain.order.create"] },
  "orders/d2h/standard-order-catalog": { kind: 'ENTERPRISE', permissions: ["supply_chain.order.create"] },
  "orders/delete": { kind: 'ENTERPRISE', permissions: ["platform.data.destructive"], via: ["lib/server/destructive-ops-guard.ts"] },
  "orders/from-ellbow": { kind: 'SERVICE', reason: "Webhook / integration authenticated by a registered service credential (sa_service_identities)" },
  "organization/update-bank-details": { kind: 'ENTERPRISE', permissions: ["platform.organization.manage"] },
  "organizations/delete": { kind: 'ENTERPRISE', permissions: ["platform.data.destructive"], via: ["lib/server/destructive-ops-guard.ts"] },
  "organizations/delete/request-otp": { kind: 'ENTERPRISE', permissions: ["platform.organization.manage"] },
  "organizations/delete/verify-and-delete": { kind: 'ENTERPRISE', permissions: ["platform.data.destructive"] },
  "organizations/import": { kind: 'ENTERPRISE', permissions: ["platform.organization.manage"] },
  "organizations/set-default-warehouse": { kind: 'ENTERPRISE', permissions: ["platform.organization.manage"] },
  "outdoor/contact": { kind: 'EXCEPTION', reason: "Public contact form (POST); staff inbox (GET) uses the Outdoor store staff rule \u2014 see outdoor/fulfilment" },
  "outdoor/fulfilment": { kind: 'EXCEPTION', reason: "Outdoor store staff route (staging-only feature, not yet on main): requireOutdoorStaff HQ/role-level rule. Mapping to ecommerce.order.manage/store.manage (max level 20) would remove 6 HQ Managers; kept as-is pending a management decision on who operates the Outdoor store" },
  "outdoor/fulfilment/access": { kind: 'EXCEPTION', reason: "Outdoor store staff route (staging-only feature, not yet on main): requireOutdoorStaff HQ/role-level rule. Mapping to ecommerce.order.manage/store.manage (max level 20) would remove 6 HQ Managers; kept as-is pending a management decision on who operates the Outdoor store" },
  "outdoor/newsletter": { kind: 'PUBLIC', reason: "Public newsletter sign-up (email capture, no account data returned)" },
  "outdoor/newsletter/unsubscribe": { kind: 'PUBLIC', reason: "Public newsletter unsubscribe" },
  "outdoor/password-reset/request": { kind: 'PUBLIC', reason: "Outdoor shopper password reset request (authentication flow)" },
  "outdoor/products": { kind: 'EXCEPTION', reason: "Outdoor store staff route (staging-only feature, not yet on main): requireOutdoorStaff HQ/role-level rule. Mapping to ecommerce.order.manage/store.manage (max level 20) would remove 6 HQ Managers; kept as-is pending a management decision on who operates the Outdoor store" },
  "outdoor/products/image": { kind: 'EXCEPTION', reason: "Outdoor store staff route (staging-only feature, not yet on main): requireOutdoorStaff HQ/role-level rule. Mapping to ecommerce.order.manage/store.manage (max level 20) would remove 6 HQ Managers; kept as-is pending a management decision on who operates the Outdoor store" },
  "outdoor/register/complete": { kind: 'PUBLIC', reason: "Outdoor shopper sign-up completion (verification code flow)" },
  "outdoor/register/request-code": { kind: 'PUBLIC', reason: "Outdoor shopper sign-up verification code request" },
  "outdoor/updates": { kind: 'EXCEPTION', reason: "Outdoor store staff route (staging-only feature, not yet on main): requireOutdoorStaff HQ/role-level rule. Mapping to ecommerce.order.manage/store.manage (max level 20) would remove 6 HQ Managers; kept as-is pending a management decision on who operates the Outdoor store" },
  "product-catalog/roadtour/bulk": { kind: 'ENTERPRISE', permissions: ["roadtour.campaign.manage"], via: ["lib/server/roadtour-catalog.ts"] },
  "product-catalog/roadtour/catalog": { kind: 'ENTERPRISE', permissions: ["roadtour.campaign.manage"], via: ["lib/server/roadtour-catalog.ts"] },
  "product-catalog/roadtour/category-rules": { kind: 'ENTERPRISE', permissions: ["roadtour.campaign.manage"], via: ["lib/server/roadtour-catalog.ts"] },
  "product-catalog/roadtour/products/[productId]": { kind: 'ENTERPRISE', permissions: ["roadtour.campaign.manage"], via: ["lib/server/roadtour-catalog.ts"] },
  "product-variants/validate-product-code": { kind: 'ENTERPRISE', permissions: ["product.catalog.manage"] },
  "products/variants/[variantId]/kkm-certificate": { kind: 'ENTERPRISE', permissions: ["inventory.stock_config.manage", "product.catalog.manage"], via: ["lib/server/stock-config-admin.ts"] },
  "qr-batches/download": { kind: 'ENTERPRISE', permissions: ["qr.batch.manage"] },
  "qr-batches/generate": { kind: 'ENTERPRISE', permissions: ["qr.batch.manage"] },
  "qr-batches/process": { kind: 'ENTERPRISE', permissions: ["qr.batch.manage"] },
  "qr-monitoring/stats": { kind: 'ENTERPRISE', permissions: ["qr.batch.manage"] },
  "qr/batches/[batchId]/progress": { kind: 'ENTERPRISE', permissions: ["qr.batch.manage"] },
  "qr/master/recalculate": { kind: 'ENTERPRISE', permissions: ["manufacturing.production.manage"] },
  "qr/verify-security-code": { kind: 'PUBLIC', reason: "Public consumer journey, QR verification and branding content" },
  "reference/search": { kind: 'PUBLIC', reason: "Public consumer journey, QR verification and branding content" },
  "reporting/consumer-analytics": { kind: 'ENTERPRISE', permissions: ["reporting.analytics.view"] },
  "reporting/consumer-analytics/periods": { kind: 'ENTERPRISE', permissions: ["reporting.analytics.view"] },
  "reporting/distributor-analytics": { kind: 'ENTERPRISE', permissions: ["reporting.analytics.view"] },
  "reporting/distributor-analytics/csv": { kind: 'ENTERPRISE', permissions: ["reporting.analytics.view"] },
  "reporting/distributor-analytics/drilldown": { kind: 'ENTERPRISE', permissions: ["reporting.analytics.view"] },
  "reporting/distributor-analytics/filters": { kind: 'ENTERPRISE', permissions: ["reporting.analytics.view"] },
  "reporting/distributors/[id]": { kind: 'ENTERPRISE', permissions: ["reporting.analytics.view"] },
  "reporting/distributors/csv": { kind: 'ENTERPRISE', permissions: ["reporting.analytics.view"] },
  "reporting/distributors/report": { kind: 'ENTERPRISE', permissions: ["reporting.analytics.view"] },
  "reporting/product-analytics": { kind: 'ENTERPRISE', permissions: ["reporting.analytics.view"] },
  "reporting/product-analytics/filters": { kind: 'ENTERPRISE', permissions: ["reporting.analytics.view"] },
  "reporting/shop-by-negeri/excel": { kind: 'ENTERPRISE', permissions: ["reporting.analytics.view"] },
  "reporting/shop-performance/periods": { kind: 'ENTERPRISE', permissions: ["reporting.analytics.view"] },
  "reporting/stats": { kind: 'ENTERPRISE', permissions: ["reporting.analytics.view"] },
  "returns": { kind: 'ENTERPRISE', permissions: ["inventory.return.manage", "inventory.return.request"], via: ["lib/returns/server.ts"] },
  "returns/[id]": { kind: 'ENTERPRISE', permissions: ["inventory.return.manage", "inventory.return.request"], via: ["lib/returns/server.ts"] },
  "returns/[id]/status": { kind: 'ENTERPRISE', permissions: ["inventory.return.manage", "inventory.return.request"], via: ["lib/returns/server.ts"] },
  "returns/eligible-products": { kind: 'ENTERPRISE', permissions: ["inventory.return.manage"], via: ["lib/returns/server.ts"] },
  "returns/meta": { kind: 'ENTERPRISE', permissions: ["inventory.return.manage"], via: ["lib/returns/server.ts"] },
  "returns/organizations": { kind: 'ENTERPRISE', permissions: ["inventory.return.manage"], via: ["lib/returns/server.ts"] },
  "returns/reporting": { kind: 'ENTERPRISE', permissions: ["inventory.return.manage"], via: ["lib/returns/server.ts"] },
  "returns/reporting/email": { kind: 'ENTERPRISE', permissions: ["inventory.return.manage"], via: ["lib/returns/server.ts"] },
  "returns/reporting/export": { kind: 'ENTERPRISE', permissions: ["inventory.return.manage"], via: ["lib/returns/server.ts"] },
  "returns/reporting/summary": { kind: 'ENTERPRISE', permissions: ["inventory.return.manage"], via: ["lib/returns/server.ts"] },
  "returns/settings": { kind: 'ENTERPRISE', permissions: ["inventory.return.manage"], via: ["lib/returns/server.ts"] },
  "roadtour/claim-reward": { kind: 'PUBLIC', reason: "Public RoadTour participant experience (token-bound)" },
  "roadtour/events": { kind: 'ENTERPRISE', permissions: ["roadtour.campaign.manage"] },
  "roadtour/events/[eventId]": { kind: 'ENTERPRISE', permissions: ["roadtour.campaign.manage"] },
  "roadtour/kpi/cycles": { kind: 'ENTERPRISE', permissions: ["roadtour.kpi.manage"], via: ["app/api/roadtour/kpi/_lib.ts"] },
  "roadtour/kpi/cycles/[cycleId]": { kind: 'ENTERPRISE', permissions: ["roadtour.kpi.manage"], via: ["app/api/roadtour/kpi/_lib.ts"] },
  "roadtour/kpi/cycles/[cycleId]/activate": { kind: 'ENTERPRISE', permissions: ["roadtour.kpi.manage"], via: ["app/api/roadtour/kpi/_lib.ts"] },
  "roadtour/kpi/cycles/duplicate": { kind: 'ENTERPRISE', permissions: ["roadtour.kpi.manage"], via: ["app/api/roadtour/kpi/_lib.ts"] },
  "roadtour/kpi/plans": { kind: 'ENTERPRISE', permissions: ["roadtour.kpi.manage"], via: ["app/api/roadtour/kpi/_lib.ts"] },
  "roadtour/kpi/plans/[planId]": { kind: 'ENTERPRISE', permissions: ["roadtour.kpi.manage"], via: ["app/api/roadtour/kpi/_lib.ts"] },
  "roadtour/kpi/plans/[planId]/activate": { kind: 'ENTERPRISE', permissions: ["roadtour.kpi.manage"], via: ["app/api/roadtour/kpi/_lib.ts"] },
  "roadtour/kpi/report": { kind: 'ENTERPRISE', permissions: ["roadtour.kpi.manage", "roadtour.report.view"], via: ["app/api/roadtour/kpi/_lib.ts"] },
  "roadtour/kpi/report/excel": { kind: 'ENTERPRISE', permissions: ["roadtour.kpi.manage", "roadtour.report.view"], via: ["app/api/roadtour/kpi/_lib.ts"] },
  "roadtour/kpi/rules": { kind: 'ENTERPRISE', permissions: ["roadtour.kpi.manage"], via: ["app/api/roadtour/kpi/_lib.ts"] },
  "roadtour/kpi/rules/[ruleId]": { kind: 'ENTERPRISE', permissions: ["roadtour.kpi.manage"], via: ["app/api/roadtour/kpi/_lib.ts"] },
  "roadtour/kpi/teams": { kind: 'ENTERPRISE', permissions: ["roadtour.kpi.manage"], via: ["app/api/roadtour/kpi/_lib.ts"] },
  "roadtour/kpi/teams/[teamId]": { kind: 'ENTERPRISE', permissions: ["roadtour.kpi.manage"], via: ["app/api/roadtour/kpi/_lib.ts"] },
  "roadtour/products": { kind: 'PUBLIC', reason: "Public RoadTour participant experience (token-bound)" },
  "roadtour/qr-image/[token]": { kind: 'PUBLIC', reason: "Public RoadTour participant experience (token-bound)" },
  "roadtour/reporting/monthly": { kind: 'ENTERPRISE', permissions: ["roadtour.kpi.manage", "roadtour.report.view"], via: ["app/api/roadtour/kpi/_lib.ts"] },
  "roadtour/reporting/shop-performance": { kind: 'ENTERPRISE', permissions: ["roadtour.kpi.manage", "roadtour.report.view"], via: ["app/api/roadtour/kpi/_lib.ts"] },
  "roadtour/send-qr-whatsapp": { kind: 'ENTERPRISE', permissions: ["platform.settings.manage", "roadtour.campaign.manage"], via: ["app/api/settings/whatsapp/_utils.ts"] },
  "roadtour/settings-status": { kind: 'ENTERPRISE', permissions: ["roadtour.report.view"] },
  "roadtour/test-claim-alert": { kind: 'ENTERPRISE', permissions: ["platform.settings.manage", "roadtour.campaign.manage"], via: ["app/api/settings/whatsapp/_utils.ts"] },
  "roadtour/visits/participants": { kind: 'ENTERPRISE', permissions: ["roadtour.kpi.manage", "roadtour.visit.manage"], via: ["app/api/roadtour/kpi/_lib.ts"] },
  "scan-issues": { kind: 'ENTERPRISE', permissions: ["customer.support.manage"] },
  "scan-issues/[id]": { kind: 'ENTERPRISE', permissions: ["customer.support.manage"] },
  "scan-issues/[id]/notify": { kind: 'ENTERPRISE', permissions: ["customer.support.manage"] },
  "scan-issues/settings": { kind: 'ENTERPRISE', permissions: ["customer.support.manage"] },
  "scan-issues/templates": { kind: 'ENTERPRISE', permissions: ["customer.support.manage"] },
  "scratch-card/claim": { kind: 'CONSUMER', reason: "Consumer loyalty/scan experience (consumer identity, not enterprise RBAC)" },
  "scratch-card/play": { kind: 'CONSUMER', reason: "Consumer loyalty/scan experience (consumer identity, not enterprise RBAC)" },
  "security-access/access-requests": { kind: 'ENTERPRISE', permissions: ["security.access_request.approve"] },
  "security-access/assignments": { kind: 'ENTERPRISE', permissions: ["security.role.assign"] },
  "security-access/delegations": { kind: 'ENTERPRISE', permissions: ["security.delegation.manage"] },
  "security-access/governance": { kind: 'ENTERPRISE', permissions: ["security.audit.view"] },
  "security-access/modes": { kind: 'ENTERPRISE', permissions: ["security.permission.manage"] },
  "security-access/overview": { kind: 'ENTERPRISE', permissions: ["security.access.view"] },
  "security-access/pilot/transfer-shadow": { kind: 'ENTERPRISE', permissions: ["inventory.transfer.approve", "inventory.transfer.dispatch", "inventory.transfer.receive", "inventory.transfer.request"] },
  "security-access/reviews": { kind: 'ENTERPRISE', permissions: ["security.access_review.manage"] },
  "security-access/roles": { kind: 'ENTERPRISE', permissions: ["security.role.manage"] },
  "security-access/scopes": { kind: 'ENTERPRISE', permissions: ["security.scope.manage"] },
  "security-access/simulate": { kind: 'ENTERPRISE', permissions: ["security.access.view"] },
  "security-access/sod": { kind: 'ENTERPRISE', permissions: ["security.audit.view", "security.policy.manage"] },
  "serapp/cancel-hold": { kind: 'ENTERPRISE', permissions: ["supply_chain.order.cancel"], via: ["lib/serapp/assistant-actions.ts"] },
  "serapp/catalog-search": { kind: 'ENTERPRISE', permissions: ["supply_chain.order.create"], via: ["lib/serapp/order-context.ts"] },
  "serapp/confirm-order": { kind: 'ENTERPRISE', permissions: ["supply_chain.order.create"], via: ["lib/serapp/order-context.ts"] },
  "serapp/conversations": { kind: 'ENTERPRISE', permissions: ["supply_chain.order.create"], via: ["lib/serapp/chat-auth.ts"] },
  "serapp/conversations/[id]": { kind: 'ENTERPRISE', permissions: ["supply_chain.order.create"], via: ["lib/serapp/chat-auth.ts"] },
  "serapp/conversations/[id]/attachments": { kind: 'ENTERPRISE', permissions: ["supply_chain.order.create"], via: ["lib/serapp/chat-auth.ts"] },
  "serapp/conversations/[id]/messages": { kind: 'ENTERPRISE', permissions: ["supply_chain.order.create"], via: ["lib/serapp/chat-auth.ts"] },
  "serapp/conversations/[id]/resolve-line": { kind: 'ENTERPRISE', permissions: ["supply_chain.order.create"], via: ["lib/serapp/chat-auth.ts", "lib/serapp/order-context.ts"] },
  "serapp/do-status": { kind: 'ENTERPRISE', permissions: ["supply_chain.order.create"] },
  "serapp/history": { kind: 'ENTERPRISE', permissions: ["supply_chain.order.create"] },
  "serapp/notify-order-approved": { kind: 'ENTERPRISE', permissions: ["supply_chain.order.approve"] },
  "serapp/paste-check": { kind: 'ENTERPRISE', permissions: ["supply_chain.order.create"], via: ["lib/serapp/order-context.ts"] },
  "serapp/presence": { kind: 'ENTERPRISE', permissions: ["supply_chain.order.create"], via: ["lib/serapp/chat-auth.ts"] },
  "serapp/warehouse-accept": { kind: 'ENTERPRISE', permissions: ["warehouse.shipment.manage"] },
  "settings/ai-provider": { kind: 'ENTERPRISE', permissions: ["platform.settings.manage"] },
  "settings/ai-provider/test": { kind: 'ENTERPRISE', permissions: ["platform.settings.manage"] },
  "settings/ai-usage": { kind: 'ENTERPRISE', permissions: ["platform.settings.manage"] },
  "settings/notifications/email-activity": { kind: 'ENTERPRISE', permissions: ["platform.settings.manage"] },
  "settings/notifications/providers": { kind: 'ENTERPRISE', permissions: ["platform.settings.manage"], via: ["app/api/settings/whatsapp/_utils.ts"] },
  "settings/notifications/providers/email/test": { kind: 'ENTERPRISE', permissions: ["platform.settings.manage"] },
  "settings/notifications/providers/status": { kind: 'ENTERPRISE', permissions: ["platform.settings.manage"] },
  "settings/notifications/providers/whatsapp/default": { kind: 'ENTERPRISE', permissions: ["platform.settings.manage"], via: ["app/api/settings/whatsapp/_utils.ts"] },
  "settings/notifications/providers/whatsapp/meta/status": { kind: 'ENTERPRISE', permissions: ["platform.settings.manage"], via: ["app/api/settings/whatsapp/_utils.ts"] },
  "settings/notifications/providers/whatsapp/meta/test": { kind: 'ENTERPRISE', permissions: ["platform.settings.manage"], via: ["app/api/settings/whatsapp/_utils.ts"] },
  "settings/notifications/sms-activity": { kind: 'ENTERPRISE', permissions: ["platform.settings.manage"] },
  "settings/notifications/sms-activity/refresh-status": { kind: 'ENTERPRISE', permissions: ["platform.settings.manage"] },
  "settings/notifications/whatsapp-recovery/records": { kind: 'ENTERPRISE', permissions: ["platform.settings.manage"], via: ["app/api/settings/whatsapp/_utils.ts"] },
  "settings/notifications/whatsapp-recovery/records/clear": { kind: 'ENTERPRISE', permissions: ["platform.settings.manage"], via: ["app/api/settings/whatsapp/_utils.ts"] },
  "settings/notifications/whatsapp-recovery/send": { kind: 'ENTERPRISE', permissions: ["platform.settings.manage"], via: ["app/api/settings/whatsapp/_utils.ts"] },
  "settings/notifications/whatsapp-recovery/summary": { kind: 'ENTERPRISE', permissions: ["platform.settings.manage"], via: ["app/api/settings/whatsapp/_utils.ts"] },
  "settings/notifications/whatsapp-recovery/templates": { kind: 'ENTERPRISE', permissions: ["platform.settings.manage"], via: ["app/api/settings/whatsapp/_utils.ts"] },
  "settings/whatsapp/clear": { kind: 'ENTERPRISE', permissions: ["platform.settings.manage"], via: ["app/api/settings/whatsapp/_utils.ts"] },
  "settings/whatsapp/logout": { kind: 'ENTERPRISE', permissions: ["platform.settings.manage"], via: ["app/api/settings/whatsapp/_utils.ts"] },
  "settings/whatsapp/qr": { kind: 'ENTERPRISE', permissions: ["platform.settings.manage"], via: ["app/api/settings/whatsapp/_utils.ts"] },
  "settings/whatsapp/reconnect": { kind: 'ENTERPRISE', permissions: ["platform.settings.manage"], via: ["app/api/settings/whatsapp/_utils.ts"] },
  "settings/whatsapp/reset": { kind: 'ENTERPRISE', permissions: ["platform.settings.manage"], via: ["app/api/settings/whatsapp/_utils.ts"] },
  "settings/whatsapp/send": { kind: 'ENTERPRISE', permissions: ["platform.settings.manage"], via: ["app/api/settings/whatsapp/_utils.ts"] },
  "settings/whatsapp/start": { kind: 'ENTERPRISE', permissions: ["platform.settings.manage"], via: ["app/api/settings/whatsapp/_utils.ts"] },
  "settings/whatsapp/status": { kind: 'ENTERPRISE', permissions: ["platform.settings.manage"], via: ["app/api/settings/whatsapp/_utils.ts"] },
  "settings/whatsapp/test": { kind: 'ENTERPRISE', permissions: ["platform.settings.manage"], via: ["app/api/settings/whatsapp/_utils.ts"] },
  "shipping/easyparcel/oauth/callback": { kind: 'EXCEPTION', reason: "Outdoor store staff route (staging-only feature, not yet on main): requireOutdoorStaff HQ/role-level rule. Mapping to ecommerce.order.manage/store.manage (max level 20) would remove 6 HQ Managers; kept as-is pending a management decision on who operates the Outdoor store" },
  "shipping/easyparcel/oauth/connect": { kind: 'EXCEPTION', reason: "Outdoor store staff route (staging-only feature, not yet on main): requireOutdoorStaff HQ/role-level rule. Mapping to ecommerce.order.manage/store.manage (max level 20) would remove 6 HQ Managers; kept as-is pending a management decision on who operates the Outdoor store" },
  "shipping/easyparcel/rates": { kind: 'PUBLIC', reason: "Checkout shipping rate quote (no stored data read or written)" },
  "shop-requests": { kind: 'ENTERPRISE', permissions: ["customer.shop.manage"] },
  "shops/contact-verification/create": { kind: 'PUBLIC', reason: "Public shop self-registration (before an account exists)" },
  "shops/contact-verification/request-code": { kind: 'PUBLIC', reason: "Public shop self-registration (before an account exists)" },
  "shops/contact-verification/resend-code": { kind: 'PUBLIC', reason: "Public shop self-registration (before an account exists)" },
  "shops/contact-verification/verify-code": { kind: 'PUBLIC', reason: "Public shop self-registration (before an account exists)" },
  "shops/create": { kind: 'CONSUMER', reason: "Shop creates its own shop profile during onboarding" },
  "shops/locations": { kind: 'PUBLIC', reason: "Public shop self-registration (before an account exists)" },
  "shops/prepare-registration": { kind: 'PUBLIC', reason: "Public shop self-registration (before an account exists)" },
  "shops/search": { kind: 'PUBLIC', reason: "Public shop self-registration (before an account exists)" },
  "storefront/banners": { kind: 'PUBLIC', reason: "Public storefront catalogue and checkout" },
  "storefront/checkout": { kind: 'PUBLIC', reason: "Public storefront catalogue and checkout" },
  "storefront/orders/lookup": { kind: 'CONSUMER', reason: "Storefront shopper order lookup (own order by reference / signed-in shopper)" },
  "storefront/orders/mine": { kind: 'CONSUMER', reason: "Signed-in storefront shopper's own orders" },
  "storefront/orders/resume-payment": { kind: 'CONSUMER', reason: "Storefront shopper resumes payment of their own pending order" },
  "storefront/payment/methods": { kind: 'PUBLIC', reason: "Checkout payment method list (public configuration)" },
  "storefront/payment/webhook": { kind: 'SERVICE', reason: "Webhook / integration authenticated by a registered service credential (sa_service_identities)" },
  "support/bot/draft/[phone]": { kind: 'SERVICE', reason: "Agent API authenticated by AGENT_API_KEY / WHATSAPP_AGENT_KEY (registered service identity)" },
  "support/bot/draft/[phone]/send": { kind: 'SERVICE', reason: "Agent API authenticated by AGENT_API_KEY / WHATSAPP_AGENT_KEY (registered service identity)" },
  "support/bot/mode/[phone]": { kind: 'SERVICE', reason: "Agent API authenticated by AGENT_API_KEY / WHATSAPP_AGENT_KEY (registered service identity)" },
  "support/conversations": { kind: 'CONSUMER', reason: "User support inbox — the caller's own conversations and threads" },
  "support/conversations/[id]": { kind: 'CONSUMER', reason: "User support inbox — the caller's own conversations and threads" },
  "support/conversations/[id]/messages": { kind: 'CONSUMER', reason: "User support inbox — the caller's own conversations and threads" },
  "support/conversations/[id]/read": { kind: 'CONSUMER', reason: "User support inbox — the caller's own conversations and threads" },
  "support/threads": { kind: 'CONSUMER', reason: "User support inbox — the caller's own conversations and threads" },
  "support/threads/[id]": { kind: 'CONSUMER', reason: "User support inbox — the caller's own conversations and threads" },
  "support/threads/[id]/messages": { kind: 'CONSUMER', reason: "User support inbox — the caller's own conversations and threads" },
  "support/threads/[id]/read": { kind: 'CONSUMER', reason: "User support inbox — the caller's own conversations and threads" },
  "support/unread-count": { kind: 'CONSUMER', reason: "User support inbox — the caller's own conversations and threads" },
  "support/unread-summary": { kind: 'CONSUMER', reason: "User support inbox — the caller's own conversations and threads" },
  "support/whatsapp/ingest": { kind: 'SERVICE', reason: "Webhook / integration authenticated by a registered service credential (sa_service_identities)" },
  "support/whatsapp/send": { kind: 'ENTERPRISE', permissions: ["customer.support.manage"] },
  "telegram/link-token": { kind: 'SELF', reason: "Caller's own profile, session and notification linking only" },
  "telegram/status": { kind: 'SELF', reason: "Caller's own profile, session and notification linking only" },
  "telegram/webhook": { kind: 'SERVICE', reason: "Webhook / integration authenticated by a registered service credential (sa_service_identities)" },
  "update-login-ip": { kind: 'SELF', reason: "Caller's own profile, session and notification linking only" },
  "user/lookup-phone": { kind: 'SELF', reason: "Caller's own profile, session and notification linking only" },
  "user/profile": { kind: 'SELF', reason: "Caller's own profile, session and notification linking only" },
  "user/update-auth": { kind: 'EMPTY', reason: "Route file has no handlers" },
  "user/update-phone": { kind: 'SELF', reason: "Retired (410 Gone, Identity Foundation Stage 1): performs no write; phone changes go through user/update-profile" },
  "user/update-profile": { kind: 'SELF', reason: "Caller's own profile, session and notification linking only" },
  "users/[id]/hr": { kind: 'ENTERPRISE', permissions: ["hr.employee.manage"] },
  "users/reset-password": { kind: 'ENTERPRISE', permissions: ["platform.user.manage"] },
  "users/search": { kind: 'ENTERPRISE', permissions: ["platform.user.manage"] },
  "verify/[code]": { kind: 'PUBLIC', reason: "Public consumer journey, QR verification and branding content" },
  "wa/marketing/audience/org-types": { kind: 'ENTERPRISE', permissions: ["customer.campaign.manage"] },
  "wa/marketing/audience/resolve": { kind: 'ENTERPRISE', permissions: ["customer.campaign.manage"] },
  "wa/marketing/audience/search": { kind: 'ENTERPRISE', permissions: ["customer.campaign.manage"] },
  "wa/marketing/audience/states": { kind: 'ENTERPRISE', permissions: ["customer.campaign.manage"] },
  "wa/marketing/campaigns": { kind: 'ENTERPRISE', permissions: ["customer.campaign.manage"] },
  "wa/marketing/campaigns/[id]": { kind: 'ENTERPRISE', permissions: ["customer.campaign.manage"] },
  "wa/marketing/campaigns/[id]/launch": { kind: 'ENTERPRISE', permissions: ["customer.campaign.manage"] },
  "wa/marketing/campaigns/[id]/run-now": { kind: 'ENTERPRISE', permissions: ["customer.campaign.manage"] },
  "wa/marketing/reporting/preview": { kind: 'ENTERPRISE', permissions: ["customer.campaign.manage"] },
  "wa/marketing/safety-presets": { kind: 'ENTERPRISE', permissions: ["customer.campaign.manage"] },
  "wa/marketing/safety-presets/[id]": { kind: 'ENTERPRISE', permissions: ["customer.campaign.manage"] },
  "wa/marketing/safety/apply": { kind: 'ENTERPRISE', permissions: ["customer.campaign.manage"] },
  "wa/marketing/segments": { kind: 'ENTERPRISE', permissions: ["customer.campaign.manage"] },
  "wa/marketing/segments/[id]": { kind: 'ENTERPRISE', permissions: ["customer.campaign.manage"] },
  "wa/marketing/send-logs": { kind: 'ENTERPRISE', permissions: ["customer.campaign.manage"] },
  "wa/marketing/send-logs/[id]": { kind: 'ENTERPRISE', permissions: ["customer.campaign.manage"] },
  "wa/marketing/settings": { kind: 'ENTERPRISE', permissions: ["customer.campaign.manage"] },
  "wa/marketing/templates": { kind: 'ENTERPRISE', permissions: ["customer.campaign.manage"] },
  "wa/marketing/test-send": { kind: 'ENTERPRISE', permissions: ["customer.campaign.manage"] },
  "warehouse/active-orders": { kind: 'ENTERPRISE', permissions: ["inventory.report.view"] },
  "warehouse/cancel-shipment": { kind: 'ENTERPRISE', permissions: ["warehouse.shipment.manage"], via: ["lib/warehouse/shipment-route-guard.ts"] },
  "warehouse/complete-shipment": { kind: 'ENTERPRISE', permissions: ["warehouse.shipment.manage"], via: ["lib/warehouse/shipment-route-guard.ts"] },
  "warehouse/confirm-receipt": { kind: 'ENTERPRISE', permissions: ["warehouse.receipt.post"] },
  "warehouse/confirm-shipment": { kind: 'ENTERPRISE', permissions: ["warehouse.shipment.manage"] },
  "warehouse/debug-history": { kind: 'ENTERPRISE', permissions: ["inventory.report.view"] },
  "warehouse/debug-worker": { kind: 'SERVICE', reason: "Cron/queue worker authenticated with CRON_SECRET (registered service identity)" },
  "warehouse/grn-history": { kind: 'ENTERPRISE', permissions: ["inventory.report.view"] },
  "warehouse/intake-history": { kind: 'ENTERPRISE', permissions: ["inventory.report.view"] },
  "warehouse/pending-receives": { kind: 'ENTERPRISE', permissions: ["inventory.report.view"] },
  "warehouse/receipt-history": { kind: 'ENTERPRISE', permissions: ["inventory.report.view"] },
  "warehouse/receipt-summary": { kind: 'ENTERPRISE', permissions: ["inventory.report.view"] },
  "warehouse/receive-master": { kind: 'ENTERPRISE', permissions: ["warehouse.receipt.post"] },
  "warehouse/receiving-status": { kind: 'ENTERPRISE', permissions: ["inventory.report.view"] },
  "warehouse/reset-receiving": { kind: 'ENTERPRISE', permissions: ["warehouse.receipt.post"] },
  "warehouse/scan-batch-for-shipment": { kind: 'ENTERPRISE', permissions: ["warehouse.shipment.manage"], via: ["lib/warehouse/shipment-route-guard.ts"] },
  "warehouse/scan-for-shipment": { kind: 'ENTERPRISE', permissions: ["warehouse.shipment.manage"], via: ["lib/warehouse/shipment-route-guard.ts"] },
  "warehouse/scan-history": { kind: 'ENTERPRISE', permissions: ["inventory.report.view"] },
  "warehouse/scanned-codes": { kind: 'ENTERPRISE', permissions: ["inventory.report.view"] },
  "warehouse/shipping-history": { kind: 'ENTERPRISE', permissions: ["inventory.report.view"] },
  "warehouse/simple-check": { kind: 'ENTERPRISE', permissions: ["inventory.report.view"] },
  "warehouse/start-receiving": { kind: 'ENTERPRISE', permissions: ["warehouse.receipt.post"] },
  "warehouse/start-shipment": { kind: 'ENTERPRISE', permissions: ["warehouse.shipment.manage"], via: ["lib/warehouse/shipment-route-guard.ts"] },
  "warehouse/test-raw-query": { kind: 'ENTERPRISE', permissions: ["platform.data.destructive"] },
  "warehouse/unlink-product-from-sessions": { kind: 'ENTERPRISE', permissions: ["warehouse.shipment.manage"], via: ["lib/warehouse/shipment-route-guard.ts"] },
  "warehouse/unlink-shipment-code": { kind: 'ENTERPRISE', permissions: ["warehouse.shipment.manage"], via: ["lib/warehouse/shipment-route-guard.ts"] },
  "webhooks/sms-gateway": { kind: 'SERVICE', reason: "Webhook / integration authenticated by a registered service credential (sa_service_identities)" },
  "webhooks/whatsapp/meta": { kind: 'SERVICE', reason: "Webhook / integration authenticated by a registered service credential (sa_service_identities)" },
}
