'use client'

import { useCallback, useEffect, useState } from 'react'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { Dialog, DialogContent, DialogFooter, DialogHeader, DialogTitle } from '@/components/ui/dialog'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select'
import { useToast } from '@/components/ui/use-toast'

type Report = 'shops' | 'shop-staff' | 'consumers' | 'redemptions' | 'referrals'
export function EllbowReportPanel({ report }: { report: Report }) {
  const [rows, setRows] = useState<any[]>([]); const [loading, setLoading] = useState(true); const [search, setSearch] = useState(''); const [status, setStatus] = useState('all'); const [adjusting, setAdjusting] = useState<any>(null); const [delta, setDelta] = useState(''); const [reason, setReason] = useState(''); const { toast } = useToast()
  const load = useCallback(async () => { setLoading(true); try { const query = new URLSearchParams(); if (search) query.set('search', search); if (report === 'redemptions') query.set('status', status); const response = await fetch(`/api/engagement/catalog/ellbow/reports/${report}?${query}`); const body = await response.json(); if (!response.ok) throw new Error(body.error); setRows(body.rows ?? []) } catch (error) { toast({ title: 'Unable to load Ellbow report', description: error instanceof Error ? error.message : 'Unknown error', variant: 'destructive' }) } finally { setLoading(false) } }, [report, search, status, toast])
  useEffect(() => { load() }, [load])
  const adjust = async () => { const response = await fetch('/api/engagement/catalog/ellbow/adjust', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ owner_user_id: adjusting.owner_user_id, wallet_lane: adjusting.wallet_lane, points_delta: Number(delta), reason, idempotency_key: crypto.randomUUID() }) }); const body = await response.json(); if (!response.ok) return toast({ title: 'Adjustment failed', description: body.error, variant: 'destructive' }); setAdjusting(null); setDelta(''); setReason(''); toast({ title: 'Ellbow balance adjusted' }); load() }
  const updateRedemption = async (id: string, nextStatus: string) => { const response = await fetch('/api/engagement/catalog/ellbow/redemptions', { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ id, status: nextStatus }) }); const body = await response.json(); if (!response.ok) return toast({ title: 'Status update failed', description: body.error, variant: 'destructive' }); toast({ title: `Redemption ${nextStatus}` }); load() }
  const title = ({ shops: 'Shop Performance', 'shop-staff': 'Shop Staff Performance', consumers: 'Consumer Performance', redemptions: 'Redemption History', referrals: 'Referral Monitor' } as const)[report]
  return <Card><CardHeader><CardTitle>{title}</CardTitle><CardDescription>Server-scoped Ellbow Loyalty data only. No legacy point views are queried.</CardDescription><div className="flex gap-2 pt-3"><Input placeholder="Search Ellbow records…" value={search} onChange={event => setSearch(event.target.value)} />{report === 'redemptions' && <Select value={status} onValueChange={setStatus}><SelectTrigger className="w-44"><SelectValue /></SelectTrigger><SelectContent>{['all','pending','approved','fulfilled','rejected','cancelled'].map(value => <SelectItem key={value} value={value}>{value}</SelectItem>)}</SelectContent></Select>}</div></CardHeader><CardContent>{loading ? <div className="py-12 text-center text-muted-foreground">Loading…</div> : rows.length === 0 ? <div className="py-12 text-center text-muted-foreground">No Ellbow records yet.</div> : <div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b text-left text-xs uppercase text-muted-foreground"><th className="p-3">Name</th><th>Lane / status</th><th>Balance / points</th><th>Earned</th><th>Redeemed</th><th>Transactions</th><th>Last activity</th><th>Actions</th></tr></thead><tbody>{rows.map(row => <tr key={row.wallet_id || row.id || row.shop_id} className="border-b"><td className="p-3 font-medium">{row.shop_name || row.full_name || row.reward_name || row.referrer_name || 'Independent'}</td><td>{row.wallet_lane || row.status || 'shop'}</td><td>{Number(row.balance ?? row.points_used ?? row.points_awarded ?? 0).toLocaleString()}</td><td>{Number(row.total_earned ?? row.system_awards ?? 0).toLocaleString()}</td><td>{Number(row.total_redeemed ?? 0).toLocaleString()}</td><td>{Number(row.transaction_count ?? 0).toLocaleString()}</td><td>{row.last_activity_at || row.created_at ? new Date(row.last_activity_at || row.created_at).toLocaleString() : '—'}</td><td className="space-x-1">{['shop-staff','consumers'].includes(report) && <Button size="sm" variant="outline" onClick={() => setAdjusting(row)}>Adjust</Button>}{report === 'redemptions' && row.status === 'pending' && <><Button size="sm" onClick={() => updateRedemption(row.id,'approved')}>Approve</Button><Button size="sm" variant="destructive" onClick={() => updateRedemption(row.id,'rejected')}>Reject</Button></>}{report === 'redemptions' && row.status === 'approved' && <><Button size="sm" onClick={() => updateRedemption(row.id,'fulfilled')}>Fulfill</Button><Button size="sm" variant="destructive" onClick={() => updateRedemption(row.id,'cancelled')}>Cancel</Button></>}</td></tr>)}</tbody></table></div>}</CardContent>
    <Dialog open={Boolean(adjusting)} onOpenChange={open => !open && setAdjusting(null)}><DialogContent><DialogHeader><DialogTitle>Adjust Ellbow {adjusting?.wallet_lane} wallet</DialogTitle></DialogHeader><div className="space-y-4"><div><Label>Point change</Label><Input type="number" value={delta} onChange={event => setDelta(event.target.value)} placeholder="Use a negative value to deduct" /></div><div><Label>Mandatory reason</Label><Input value={reason} onChange={event => setReason(event.target.value)} /></div></div><DialogFooter><Button variant="outline" onClick={() => setAdjusting(null)}>Cancel</Button><Button onClick={adjust} disabled={!reason.trim() || !Number.isInteger(Number(delta)) || Number(delta) === 0}>Apply adjustment</Button></DialogFooter></DialogContent></Dialog>
  </Card>
}
