'use client'

import Image from 'next/image'
import { useRouter } from 'next/navigation'
import { FormEvent, useEffect, useState } from 'react'
import { ArrowDown, ArrowLeft, ArrowUp, ImagePlus, Save, Star, Trash2 } from 'lucide-react'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select'
import { Textarea } from '@/components/ui/textarea'
import { useToast } from '@/components/ui/use-toast'
import { getStorageUrl } from '@/lib/utils'

type Category = { id: string; name: string; active: boolean }
type RewardImage = { id: string; storage_path: string; sort_order: number; is_default: boolean }
type Form = { name: string; code: string; category_id: string; description: string; points_required: string; point_offer: string; stock_quantity: string; status: string; valid_from: string; valid_until: string; verification_mode: string; estimated_financial_cost_rm: string }
const empty: Form = { name: '', code: '', category_id: '', description: '', points_required: '0', point_offer: '', stock_quantity: '', status: 'paused', valid_from: '', valid_until: '', verification_mode: 'manual', estimated_financial_cost_rm: '' }

export function EllbowRewardEditor({ mode, rewardId }: { mode: 'create' | 'edit'; rewardId?: string }) {
  const [form, setForm] = useState(empty)
  const [categories, setCategories] = useState<Category[]>([])
  const [images, setImages] = useState<RewardImage[]>([])
  const [newFiles, setNewFiles] = useState<File[]>([])
  const [loading, setLoading] = useState(mode === 'edit')
  const [saving, setSaving] = useState(false)
  const [pointValueRm, setPointValueRm] = useState(0)
  const router = useRouter(); const { toast } = useToast()
  useEffect(() => { Promise.all([fetch('/api/engagement/catalog/ellbow/categories').then(async r => { const b=await r.json(); if(!r.ok) throw new Error(b.error); return b.categories }), mode === 'edit' && rewardId ? fetch(`/api/engagement/catalog/ellbow/rewards/${rewardId}`).then(async r => { const b=await r.json(); if(!r.ok) throw new Error(b.error); return b.reward }) : Promise.resolve(null)]).then(([categoryRows, reward]) => { setCategories(categoryRows.filter((category: Category) => category.active)); if (reward) { setForm({ name: reward.name, code: reward.code, category_id: reward.category_id, description: reward.description ?? '', points_required: String(reward.points_required), point_offer: reward.point_offer === null ? '' : String(reward.point_offer), stock_quantity: reward.stock_quantity === null ? '' : String(reward.stock_quantity), status: reward.status, valid_from: toInput(reward.valid_from), valid_until: toInput(reward.valid_until), verification_mode: reward.verification_mode, estimated_financial_cost_rm: reward.estimated_financial_cost_rm === null ? '' : String(reward.estimated_financial_cost_rm) }); setImages([...(reward.images ?? [])].sort((a: RewardImage,b: RewardImage) => a.sort_order-b.sort_order)) } else if (categoryRows[0]) setForm(current => ({ ...current, category_id: categoryRows[0].id })) }).catch(error => toast({ title: 'Unable to load Ellbow reward', description: error.message, variant: 'destructive' })).finally(() => setLoading(false)) }, [mode, rewardId, toast])
  useEffect(() => { fetch('/api/engagement/catalog/ellbow/settings').then(response => response.json()).then(body => setPointValueRm(Number(body.settings?.point_value_rm || 0))).catch(() => setPointValueRm(0)) }, [])
  const update = (key: keyof Form, value: string) => setForm(current => ({ ...current, [key]: value }))
  const submit = async (event: FormEvent) => { event.preventDefault(); setSaving(true); try { const response = await fetch(mode === 'edit' ? `/api/engagement/catalog/ellbow/rewards/${rewardId}` : '/api/engagement/catalog/ellbow/rewards', { method: mode === 'edit' ? 'PATCH' : 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ ...form, point_offer: form.point_offer || null, stock_quantity: form.stock_quantity || null, valid_from: form.valid_from ? new Date(form.valid_from).toISOString() : null, valid_until: form.valid_until ? new Date(form.valid_until).toISOString() : null }) }); const body = await response.json(); if (!response.ok) throw new Error(body.error); const id = body.reward.id; for (const file of newFiles) { const data = new FormData(); data.set('file', file); const upload = await fetch(`/api/engagement/catalog/ellbow/rewards/${id}/images`, { method: 'POST', body: data }); const uploadBody = await upload.json(); if (!upload.ok) throw new Error(uploadBody.error) } toast({ title: mode === 'edit' ? 'Ellbow reward updated' : 'Ellbow reward created' }); router.push('/engagement/catalog/admin?program=ellbow'); router.refresh() } catch (error) { toast({ title: 'Unable to save Ellbow reward', description: error instanceof Error ? error.message : 'Unknown error', variant: 'destructive' }) } finally { setSaving(false) } }
  const removeReward = async () => { if (!rewardId || !window.confirm('Delete this Ellbow reward? This does not affect Cellera rewards.')) return; const response = await fetch(`/api/engagement/catalog/ellbow/rewards/${rewardId}`, { method: 'DELETE' }); const body = await response.json(); if (!response.ok) return toast({ title: 'Unable to delete reward', description: body.error, variant: 'destructive' }); router.push('/engagement/catalog/admin?program=ellbow'); router.refresh() }
  const removeImage = async (image: RewardImage) => { if (!rewardId) return; const response = await fetch(`/api/engagement/catalog/ellbow/rewards/${rewardId}/images/${image.id}`, { method: 'DELETE' }); const body = await response.json(); if (!response.ok) return toast({ title: 'Unable to remove image', description: body.error, variant: 'destructive' }); const next = images.filter(item => item.id !== image.id); if (image.is_default && next[0]) next[0] = { ...next[0], is_default: true }; setImages(next) }
  const saveImageOrder = async (next: RewardImage[]) => { if (!rewardId) return; const normalized = next.map((image, sort_order) => ({ ...image, sort_order })); setImages(normalized); const response = await fetch(`/api/engagement/catalog/ellbow/rewards/${rewardId}/images`, { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ images: normalized.map(({ id, sort_order, is_default }) => ({ id, sort_order, is_default })) }) }); if (!response.ok) { const body = await response.json(); toast({ title: 'Unable to update image order', description: body.error, variant: 'destructive' }) } }
  const moveImage = (index: number, direction: -1 | 1) => { const target = index + direction; if (target < 0 || target >= images.length) return; const next = [...images]; [next[index], next[target]] = [next[target], next[index]]; saveImageOrder(next) }
  const makeDefault = (id: string) => saveImageOrder(images.map(image => ({ ...image, is_default: image.id === id })))
  const chooseFiles = (files: FileList | null) => { const selected = Array.from(files ?? []); if (images.length + newFiles.length + selected.length > 5) return toast({ title: 'Too many images', description: 'Ellbow rewards support up to 5 images.', variant: 'destructive' }); if (selected.some(file => !['image/jpeg','image/png','image/webp'].includes(file.type) || file.size > 5*1024*1024)) return toast({ title: 'Invalid image', description: 'Use JPG, PNG, or WebP images up to 5 MB.', variant: 'destructive' }); setNewFiles(current => [...current, ...selected]) }
  if (loading) return <div className="py-16 text-center text-muted-foreground">Loading Ellbow reward…</div>
  return <form onSubmit={submit} className="space-y-6">
    <div className="flex flex-wrap items-start justify-between gap-4"><div><Badge className="mb-2 bg-teal-600">Program: Ellbow Loyalty</Badge><h1 className="text-3xl font-bold">{mode === 'edit' ? 'Update Ellbow Reward' : 'Create Ellbow Reward'}</h1><p className="mt-2 text-muted-foreground">This reward belongs only to the Ellbow Pet Food loyalty program.</p></div><Button type="button" variant="outline" onClick={() => router.push('/engagement/catalog/admin?program=ellbow')}><ArrowLeft className="mr-2 h-4 w-4" />Back</Button></div>
    <Card><CardHeader><CardTitle>Reward details</CardTitle><CardDescription>Required fields and redemption-facing information.</CardDescription></CardHeader><CardContent className="grid gap-5 md:grid-cols-2">
      <Field label="Reward name"><Input value={form.name} onChange={e => update('name', e.target.value)} required /></Field><Field label="Reward code"><Input value={form.code} onChange={e => update('code', e.target.value.toUpperCase().replace(/[^A-Z0-9_-]/g,'-'))} required /></Field>
      <Field label="Ellbow reward category"><Select value={form.category_id} onValueChange={value => update('category_id', value)}><SelectTrigger><SelectValue placeholder="Select category" /></SelectTrigger><SelectContent>{categories.map(category => <SelectItem key={category.id} value={category.id}>{category.name}</SelectItem>)}</SelectContent></Select></Field>
      <Field label="Status"><Select value={form.status} onValueChange={value => update('status', value)}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{['available','scheduled','paused','expired','sold_out'].map(status => <SelectItem key={status} value={status}>{status.replace('_',' ')}</SelectItem>)}</SelectContent></Select></Field>
      <div className="md:col-span-2"><Field label="Description"><Textarea value={form.description} onChange={e => update('description', e.target.value)} rows={4} /></Field></div>
      <Field label="Points required"><Input type="number" min="0" value={form.points_required} onChange={e => update('points_required', e.target.value)} required /></Field><Field label="Point offer (optional)"><Input type="number" min="0" value={form.point_offer} onChange={e => update('point_offer', e.target.value)} /></Field>
      <Field label="Estimated fulfillment cost (RM, optional)"><Input type="number" min="0" step="0.01" value={form.estimated_financial_cost_rm} onChange={e => update('estimated_financial_cost_rm', e.target.value)} /></Field><div className={`rounded-lg border p-3 text-sm ${Number(form.estimated_financial_cost_rm || 0) > (Number(form.point_offer || form.points_required || 0) * pointValueRm) ? 'border-amber-300 bg-amber-50 text-amber-800' : 'bg-muted/30 text-muted-foreground'}`}>Estimated point value: RM {(Number(form.point_offer || form.points_required || 0) * pointValueRm).toFixed(2)}.{pointValueRm <= 0 ? ' Ellbow point value is zero.' : Number(form.estimated_financial_cost_rm || 0) > (Number(form.point_offer || form.points_required || 0) * pointValueRm) ? ' Warning: point value is below the configured fulfillment cost.' : ''}</div>
      <Field label="Stock quantity (blank = unlimited)"><Input type="number" min="0" value={form.stock_quantity} onChange={e => update('stock_quantity', e.target.value)} /></Field><Field label="Verification/approval mode"><Select value={form.verification_mode} onValueChange={value => update('verification_mode', value)}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="manual">Manual check</SelectItem><SelectItem value="automatic">Automatic</SelectItem></SelectContent></Select></Field>
      <Field label="Valid from"><Input type="datetime-local" value={form.valid_from} onChange={e => update('valid_from', e.target.value)} /></Field><Field label="Valid until"><Input type="datetime-local" value={form.valid_until} onChange={e => update('valid_until', e.target.value)} /></Field>
    </CardContent></Card>
    <Card><CardHeader><CardTitle>Reward images</CardTitle><CardDescription>Up to 5 JPG, PNG, or WebP images. Images are stored in an organization- and Ellbow-scoped path.</CardDescription></CardHeader><CardContent className="space-y-4">
      {images.map((image,index) => <div key={image.id} className="flex flex-wrap items-center gap-3 rounded border p-3"><div className="relative h-16 w-16 overflow-hidden rounded bg-muted"><Image src={getStorageUrl(image.storage_path,'avatars')} alt="Reward" fill className="object-cover" unoptimized /></div><div className="flex-1">{image.is_default ? <Badge><Star className="mr-1 h-3 w-3" />Default</Badge> : <span className="text-sm text-muted-foreground">Image {index+1}</span>}</div><Button type="button" size="icon" variant="outline" onClick={() => moveImage(index,-1)} disabled={index===0}><ArrowUp className="h-4 w-4" /></Button><Button type="button" size="icon" variant="outline" onClick={() => moveImage(index,1)} disabled={index===images.length-1}><ArrowDown className="h-4 w-4" /></Button><Button type="button" variant="outline" onClick={() => makeDefault(image.id)} disabled={image.is_default}>Set default</Button><Button type="button" size="icon" variant="destructive" onClick={() => removeImage(image)}><Trash2 className="h-4 w-4" /></Button></div>)}
      {newFiles.map((file,index) => <div key={`${file.name}-${index}`} className="flex items-center justify-between rounded border border-dashed p-3 text-sm"><span>{file.name} <span className="text-muted-foreground">(uploads when saved)</span></span><Button type="button" size="sm" variant="ghost" onClick={() => setNewFiles(files => files.filter((_,i) => i!==index))}>Remove</Button></div>)}
      {images.length + newFiles.length < 5 && <Label className="flex cursor-pointer items-center justify-center gap-2 rounded-lg border border-dashed p-6 hover:bg-muted"><ImagePlus className="h-5 w-5" />Add reward images<Input className="hidden" type="file" accept="image/jpeg,image/png,image/webp" multiple onChange={e => chooseFiles(e.target.files)} /></Label>}
    </CardContent></Card>
    <div className="flex justify-between">{mode === 'edit' ? <Button type="button" variant="destructive" onClick={removeReward}><Trash2 className="mr-2 h-4 w-4" />Delete Ellbow Reward</Button> : <span />}<Button type="submit" disabled={saving || !form.category_id}><Save className="mr-2 h-4 w-4" />{saving ? 'Saving…' : mode === 'edit' ? 'Update Ellbow Reward' : 'Create Ellbow Reward'}</Button></div>
  </form>
}

function Field({ label, children }: { label: string; children: React.ReactNode }) { return <div className="space-y-2"><Label>{label}</Label>{children}</div> }
function toInput(value: string | null) { if (!value) return ''; const date = new Date(value); const local = new Date(date.getTime() - date.getTimezoneOffset()*60000); return local.toISOString().slice(0,16) }
