'use client'

import Image from 'next/image'
import Link from 'next/link'
import { useCallback, useEffect, useMemo, useState } from 'react'
import { CalendarClock, Edit, Gift, Package, PlusCircle, Settings, Tags, TrendingUp, Users } from 'lucide-react'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from '@/components/ui/dialog'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs'
import { useToast } from '@/components/ui/use-toast'
import { getStorageUrl } from '@/lib/utils'
import { EllbowSettings } from './EllbowSettings'
import { EllbowReportPanel } from './EllbowReportPanel'
import { EllbowParticipantsPanel } from './EllbowParticipantsPanel'

type Category = { id: string; name: string; active: boolean; sort_order: number }
type RewardImage = { id: string; storage_path: string; sort_order: number; is_default: boolean }
type Reward = { id: string; name: string; code: string; points_required: number; point_offer: number | null; stock_quantity: number | null; status: string; valid_from: string | null; valid_until: string | null; verification_mode: string; category: Category; images: RewardImage[] }

export function EllbowAdminPage() {
  const [rewards, setRewards] = useState<Reward[]>([])
  const [categories, setCategories] = useState<Category[]>([])
  const [loading, setLoading] = useState(true)
  const [categoryOpen, setCategoryOpen] = useState(false)
  const [newCategory, setNewCategory] = useState('')
  const [redemptionCount, setRedemptionCount] = useState(0)
  const { toast } = useToast()
  const load = useCallback(async () => { setLoading(true); try { const [rewardResponse, categoryResponse, redemptionResponse] = await Promise.all([fetch('/api/engagement/catalog/ellbow/rewards'), fetch('/api/engagement/catalog/ellbow/categories'), fetch('/api/engagement/catalog/ellbow/reports/redemptions')]); const rewardBody = await rewardResponse.json(); const categoryBody = await categoryResponse.json(); const redemptionBody = await redemptionResponse.json(); if (!rewardResponse.ok) throw new Error(rewardBody.error); if (!categoryResponse.ok) throw new Error(categoryBody.error); setRewards(rewardBody.rewards); setCategories(categoryBody.categories); setRedemptionCount(redemptionBody.rows?.length ?? 0) } catch (error) { toast({ title: 'Unable to load Ellbow catalog', description: error instanceof Error ? error.message : 'Unknown error', variant: 'destructive' }) } finally { setLoading(false) } }, [toast])
  useEffect(() => { load() }, [load])
  const stats = useMemo(() => ({ active: rewards.filter(reward => reward.status === 'available').length, scheduled: rewards.filter(reward => reward.status === 'scheduled').length, risks: rewards.filter(reward => reward.stock_quantity !== null && reward.stock_quantity <= 10).length }), [rewards])
  const createCategory = async () => { try { const response = await fetch('/api/engagement/catalog/ellbow/categories', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ name: newCategory }) }); const body = await response.json(); if (!response.ok) throw new Error(body.error); setCategories(current => [...current, body.category]); setNewCategory(''); toast({ title: 'Ellbow category created' }) } catch (error) { toast({ title: 'Unable to create category', description: error instanceof Error ? error.message : 'Unknown error', variant: 'destructive' }) } }
  const updateCategory = async (id: string, patch: { name?: string; active?: boolean }) => { try { const response = await fetch('/api/engagement/catalog/ellbow/categories', { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ id, ...patch }) }); const body = await response.json(); if (!response.ok) throw new Error(body.error); setCategories(current => current.map(category => category.id === id ? body.category : category)); toast({ title: 'Ellbow category updated' }) } catch (error) { toast({ title: 'Unable to update category', description: error instanceof Error ? error.message : 'Unknown error', variant: 'destructive' }) } }
  return <div className="space-y-6">
    <div className="flex flex-wrap items-start justify-between gap-4"><div><div className="mb-2 flex items-center gap-2"><Badge className="bg-teal-600">Ellbow Loyalty</Badge><span className="text-sm text-muted-foreground">Pet Food loyalty program</span></div><h1 className="text-3xl font-bold">Ellbow Point Catalog Management</h1><p className="mt-2 text-muted-foreground">Manage Ellbow rewards and independent configuration. Wallets, transactions and redemption processing are not enabled.</p></div><Button asChild><Link href="/engagement/catalog/admin/new?program=ellbow"><PlusCircle className="mr-2 h-4 w-4" />Create reward</Link></Button></div>
    <Tabs defaultValue="rewards" className="space-y-5"><TabsList className="h-auto flex-wrap"><TabsTrigger value="rewards"><Package className="mr-2 h-4 w-4" />Manage Rewards</TabsTrigger><TabsTrigger value="participants"><Users className="mr-2 h-4 w-4" />Participants</TabsTrigger><TabsTrigger value="shops">Shop Performance</TabsTrigger><TabsTrigger value="staff">Shop Staff</TabsTrigger><TabsTrigger value="consumers">Consumers</TabsTrigger><TabsTrigger value="redemptions">Redemptions</TabsTrigger><TabsTrigger value="referrals">Referrals</TabsTrigger><TabsTrigger value="migration">Migration</TabsTrigger><TabsTrigger value="relationships"><Users className="mr-2 h-4 w-4" />User ↔ Shop</TabsTrigger><TabsTrigger value="settings"><Settings className="mr-2 h-4 w-4" />Settings</TabsTrigger></TabsList>
      <TabsContent value="rewards" className="space-y-5">
        <div className="grid gap-4 md:grid-cols-4"><Stat title="Active rewards" value={stats.active} icon={<Gift />} /><Stat title="Scheduled or ending soon" value={stats.scheduled} icon={<CalendarClock />} /><Stat title="Stock risks" value={stats.risks} icon={<Package />} /><Stat title="Redemptions" value={redemptionCount} icon={<TrendingUp />} /></div>
        <Card><CardHeader className="flex-row items-center justify-between"><div><CardTitle>Reward inventory</CardTitle><CardDescription>Only rewards scoped to Ellbow Loyalty are shown.</CardDescription></div><Button variant="outline" onClick={() => setCategoryOpen(true)}><Tags className="mr-2 h-4 w-4" />Manage categories</Button></CardHeader><CardContent>
          {loading ? <div className="py-16 text-center text-muted-foreground">Loading Ellbow rewards…</div> : rewards.length === 0 ? <div className="rounded-xl border border-dashed py-16 text-center"><Gift className="mx-auto mb-4 h-10 w-10 text-teal-600" /><h2 className="text-xl font-semibold">No Ellbow rewards yet</h2><p className="mt-2 text-muted-foreground">Create rewards specifically for the Ellbow Pet Food loyalty program.</p><Button asChild className="mt-5"><Link href="/engagement/catalog/admin/new?program=ellbow">Create First Reward</Link></Button></div> : <div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b text-left text-xs uppercase text-muted-foreground"><th className="p-3">Reward</th><th>Category</th><th>Points</th><th>Stock</th><th>Status</th><th>Verification</th><th>Actions</th></tr></thead><tbody>{rewards.map(reward => { const image = [...(reward.images ?? [])].sort((a,b) => a.sort_order-b.sort_order).find(item => item.is_default) ?? reward.images?.[0]; return <tr key={reward.id} className="border-b"><td className="p-3"><div className="flex items-center gap-3"><div className="relative h-12 w-12 overflow-hidden rounded border bg-muted">{image ? <Image src={getStorageUrl(image.storage_path, 'avatars')} alt="" fill className="object-cover" unoptimized /> : <Package className="m-3 h-6 w-6 text-muted-foreground" />}</div><div><div className="font-medium">{reward.name}</div><div className="text-xs text-muted-foreground">{reward.code}</div></div></div></td><td>{reward.category?.name}</td><td>{(reward.point_offer ?? reward.points_required).toLocaleString()}</td><td>{reward.stock_quantity ?? 'Unlimited'}</td><td><Badge variant="outline">{reward.status.replace('_',' ')}</Badge></td><td>{reward.verification_mode}</td><td><Button asChild size="sm" variant="outline"><Link href={`/engagement/catalog/admin/edit/${reward.id}?program=ellbow`}><Edit className="mr-1 h-4 w-4" />Edit</Link></Button></td></tr> })}</tbody></table></div>}
        </CardContent></Card>
      </TabsContent><TabsContent value="participants"><EllbowParticipantsPanel /></TabsContent><TabsContent value="shops"><EllbowReportPanel report="shops" /></TabsContent><TabsContent value="staff"><EllbowReportPanel report="shop-staff" /></TabsContent><TabsContent value="consumers"><EllbowReportPanel report="consumers" /></TabsContent><TabsContent value="redemptions"><EllbowReportPanel report="redemptions" /></TabsContent><TabsContent value="referrals"><EllbowReportPanel report="referrals" /></TabsContent><TabsContent value="migration"><Card><CardHeader><CardTitle>Point Migration</CardTitle><CardDescription>Not applicable — Ellbow Loyalty starts with a new independent balance.</CardDescription></CardHeader><CardContent>No Cellera-to-Ellbow transfer or conversion is available. Migration History is empty.</CardContent></Card></TabsContent><TabsContent value="relationships"><Card><CardHeader><CardTitle>User ↔ Shop</CardTitle><CardDescription>Existing user and shop master relationships are reused for Ellbow reporting.</CardDescription></CardHeader><CardContent>Point balances and earnings remain Ellbow-only. Legacy Shop Requests are not applicable to the Ellbow economy.</CardContent></Card></TabsContent><TabsContent value="settings"><EllbowSettings /></TabsContent>
    </Tabs>
    <Dialog open={categoryOpen} onOpenChange={setCategoryOpen}><DialogContent><DialogHeader><DialogTitle>Ellbow reward categories</DialogTitle><DialogDescription>These categories are separate from Cellera reward categories.</DialogDescription></DialogHeader><div className="space-y-2">{categories.map(category => <CategoryRow key={category.id} category={category} onUpdate={patch => updateCategory(category.id, patch)} />)}</div><div className="space-y-2"><Label>New category</Label><div className="flex gap-2"><Input value={newCategory} onChange={event => setNewCategory(event.target.value)} placeholder="Category name" /><Button onClick={createCategory} disabled={!newCategory.trim()}>Add</Button></div></div><DialogFooter><Button variant="outline" onClick={() => setCategoryOpen(false)}>Close</Button></DialogFooter></DialogContent></Dialog>
  </div>
}

function Stat({ title, value, icon, note }: { title: string; value: number; icon: React.ReactNode; note?: string }) { return <Card><CardHeader className="pb-2"><CardTitle className="flex items-center gap-2 text-base text-teal-700">{icon}{title}</CardTitle></CardHeader><CardContent><div className="text-3xl font-bold">{value}</div>{note && <div className="mt-1 text-xs text-muted-foreground">{note}</div>}</CardContent></Card> }
function CategoryRow({ category, onUpdate }: { category: Category; onUpdate: (patch: { name?: string; active?: boolean }) => void }) { const [name, setName] = useState(category.name); useEffect(() => setName(category.name), [category.name]); return <div className="flex items-center gap-2 rounded border p-2"><Input value={name} onChange={event => setName(event.target.value)} /><Button size="sm" variant="outline" onClick={() => onUpdate({ name })} disabled={!name.trim() || name === category.name}>Rename</Button><Button size="sm" variant={category.active ? 'outline' : 'secondary'} onClick={() => onUpdate({ active: !category.active })}>{category.active ? 'Disable' : 'Enable'}</Button></div> }
